[quote.epigraph, , Luke 7:47]
____
Her sins, which are many, are forgiven; for she loved much.
____

[quote.epigraph, , Gal 5:9]
____
A little leaven leaveneth the whole lump.
____

== The Life Elizabeth Ashbridge.

My life having been attended with many uncommon occurrences,
I have thought proper to make some remarks on the dealings of Divine goodness with me.
I have often had cause, with David, to say,
"`It is good for me that I have been afflicted;`" and most earnestly
desire that they who read the following lines may take warning,
and shun the evils into which I have been drawn.

I was born at Middlewich, in Cheshire, in the year 1713, of honest parents,
named Thomas and Mary Sampson.
My father bore a good character, but he was not so strictly religious as my mother,
who was a pattern of virtue to me.
I was my father`'s only child; but my mother had a son and a daughter by a former husband.
Soon after I was born, my father went to sea, and following his profession,
which was that of a surgeon, made many long voyages.
He continued in his sea-faring course of life till I was twelve years old,
so that the care of the early part of my education, devolved upon my mother;
and she discharged her duty,
in endeavouring to imbue my mind with the principles of virtue.

I have had reason to be thankful that I was blessed with such a parent;
her good advice and counsel to me have been as bread cast upon the waters.
She was an instructive example to all who knew her, and generally beloved; but,
alas! as soon as the time came,
when she might reasonably expect the benefit from her labours,
and have had comfort in me, I deserted her.

In my childhood I had an awful regard for religion and religious people,
particularly for ministers, all of whom I believed to be good men and beloved of God,
which I earnestly wished to be my own case.
I had also great tenderness for the poor,
remembering that I had read they were beloved of the Lord.
This I supposed to mean such as were poor in temporal things;
whom I often visited in their cottages,
and used to think they were better off than myself; yet, if I had money,
or any thing suitable for a gift, I bestowed it on them,
recollecting that they who gave to such, lent unto the Lord.
I made remarks on those who pretended to religion; and when I heard people swear,
I was troubled; for my mother told me, that if I used any naughty words,
God would not love me.

I observed that there were several different religious societies;
this I often thought of, and wept,
with desires that I might be directed to the one which it would be best for me to join.
In this frame of mind passed my younger years.
I was sometimes guilty of the faults common among children,
but was always sorry for what I had done amiss; and, until I was fourteen years of age,
was as innocent as most children.
About this time, my sorrows, which have continued for the greatest part of my life,
began, by my giving way to a foolish passion, in setting my affections on a young man,
who, without the leave of my parents, courted me till I consented to marry him; and,
with sorrow of heart I relate, that I suffered myself to be carried off in the night.
We were married.
My parents made all possible search for me, as soon as I was missing, but it was in vain.
This precipitate act plunged me into much sorrow.
I was soon smitten with remorse for thus leaving my parents,
whose right it was to be consulted on such an occasion.
But I was soon chastised for my disobedience, and convinced of my error.
In five months I was stripped of the darling of my heart,
and left a young and disconsolate widow.
I was now without a home.
My husband had derived his livelihood from his trade,
which was that of a stocking weaver; and my father was so displeased at my conduct,
that he would do nothing for me.
My dear mother had some compassion for me, and kept me among the neighbours.
Afterwards, by her advice, I went to a relation of hers at Dublin.
We hoped that my absence would soften my father`'s rigour; but he continued inflexible;
he would not send for me back, and I dared not to return unless he did.

The relation I went to reside with was one of the people called Quakers.
His habits were so very different from what I had been accustomed to,
that the visit proved disagreeable to me.
I had been brought up in the way of the Church of England, and though, as I have said,
I had a religious education, yet I was allowed to sing and dance,
which my cousin would not permit.
The great vivacity of my natural disposition would not, in this instance,
suffer me to give way to the gloomy sense of sorrow and conviction;
and therefore my present restraints had a wrong effect.
I became more wild and airy than ever; my cousin often reproved me;
but I then thought his conduct was the result of singularity,
and would not be controlled.
Having a distant relation in the West of Ireland, I went to him.

I now enjoyed all the liberty I wished; for,
what rendered me disagreeable to my other kinsman, was quite pleasing to this.
Between these two relations I spent three years and three months.

While I was in Ireland,
I contracted an intimate acquaintance with a widow and her daughter, who were papists.
We conversed very frequently about religion, each of us defending our peculiar tenets;
and, though I was much given to gaiety, our discussions often made me thoughtful.
The old woman told me of such mighty miracles done by their priests,
that I began to be shaken in my own belief; and thought that, if these things were so,
they must, of a truth, be the apostles`' successors.
She perceived the state of my mind, and one day exclaimed with rapture, "`Oh! if I can,
under God, be the happy instrument of converting you to the holy Catholic faith,
all the sins that ever I committed will be forgiven.`"
Sometimes I frequented her place of worship,
but none of my relations knew what was the motive.
The affair went so far, that the priest came to converse with me.
Being young, and my judgment weak, I was ready to believe what he said;
yet resolved not blindly to adopt their creed.
I thought that if their articles of faith were sound,
they would not be against my knowing them; and, therefore,
the next time I saw the priest,
I told him that I had some intention of becoming one of his flock,
but wished first to know what I must agree to.
He answered, that I must first confess my sins to him;
and gave me till the next day to consider of them.
I was not averse to this,
conscious of having done nothing for which any one could harm me;
and thinking that if what he had said was true, the confession would be for my good.
When he came again, I told all that I could remember; which, for my part,
I thought bad enough; but he considered me, he said,
the most innocent creature that ever made confession to him.
When I had done, he took a book, which he read, and told me, I was to swear I believed,
if I joined them.
I shall not trouble the reader with the recital of its ridiculous contents.
What principally made me sick of my new intention was,
that I was to swear I considered the Pretender to be king James`'s son,
and the true heir of the crown of England;
and that all who died out of the pale of the popish church, would be damned.
These doctrines startled me; I hesitated,
and desired time to take them into consideration; but, before I saw the priest again,
a change of circumstances freed me from the necessity of giving him an answer.

My father still keeping me at such a distance,
I thought myself quite excluded from his affections,
and therefore resolved not to return home.
I became acquainted with a gentlewoman, lately arrived from Pennsylvania;
who was intending to return, and, as I had an uncle, my mother`'s brother,
in this province, I soon agreed with her for my passage.
I was ignorant of the nature of an indenture, and suffered myself to be bound.
This was done privately, that it might not be found out.
As soon as it was over, she invited me to see the vessel in which I was to sail.
I readily consented, and we went on board, where there was another young woman, who,
as I afterwards found, was of a respectable family,
and had been brought there in the same way as myself.
I was pleased with the thought that I should have
such an agreeable companion in my voyage.
While we were busy conversing, my conductor went on shore, and when I wished to go,
I was not permitted.
I now saw I was kidnapped.
I was kept a prisoner in the ship three weeks,
at the end of which time my companion was found out by her friends, who fetched her away;
and by her information, my friends sent the water-bailiff, who took me on shore.
I was kept close for two weeks, but at length found means to get away.
I was so filled with the thoughts of going to America that I could not give up the design;
and meeting the captain, I inquired when he sailed; he told me, and I went on board.
There were in the ship, sixty Irish servants and several English passengers.
The latter were unacquainted with the Irish language,
which I had taken much pains to learn, and understood pretty well.
Twenty of the servants belonged to the gentlewoman abovementioned, who, with a young man,
her husband`'s brother, went with us.
While we were on the coast of Ireland, where the wind kept us some weeks,
I overheard the Irish contriving how they should be free, when they got to America.
To accomplish their design, they concluded to rise and kill the ship`'s crew,
and all the English, and to appoint the above-mentioned young man to navigate the vessel.
But, overhearing their conversation,
I discovered their barbarous intention to the captain,
who acquainted the English with it.
The next day we bore for the shore, and at a short distance from the cove of Cork,
lowered sail and dropped anchor,
under pretence that the wind was not fair for us to stand our course.
The boat was hoisted out,
and the passengers were invited to go and divert themselves on shore.
Along with others went the ringleader of the Irish.
This was all that was desired.
The rest left him, and came on board.
The captain immediately ordered his men to weigh anchor, and hoist sail.
There were great outcries for the young man on shore,
but he said that the wind had freshened up, and he would not stay for his own son.
Thus were the designs of those Irish servants rendered abortive,
in a way they did not suspect, and which it was thought advisable to keep a secret,
lest they should injure me.
At length, however, they discovered that I understood their speech,
by my smiling at a story they were telling.
From this time they devised many ways to do me mischief,
for which several of them were punished.

On the 15th of the seventh month, which was nine weeks after we left Dublin,
we arrived at New York.
Here I was betrayed by the very men whose lives I had preserved.
The captain caused an indenture to be made, and threatened me with a jail,
if I refused to sign it.
I told him that I could find means to satisfy him for my passage without becoming bound.
He replied, that I might take my choice, either to sign the indenture he showed me,
or the one I had signed in Ireland should be in force.
In a fright, I signed the former;
for I had by this time learned the character of the
woman who first induced me to think of going to America;
she was a vile creature, and I feared that if I fell into her hands,
I should be used ill.

In two weeks I was sold.
At first I had not much reason to complain of the treatment I received;
but in a short time a difference, in which I was innocent, happened,
that set my master against me, and rendered him inhuman.
It will be impossible for me to convey an adequate idea of the sufferings of my servitude.
Though my father was not rich, yet, in his house I lived well,
and I had been used to little but my school;
but now I found it would have been better for me
if I had been brought up with less indulgence.
I was not allowed decent clothes; I was obliged to perform the meanest drudgery,
and even to go barefoot in the snow.
I suffered the utmost hardship that my body was able to bear,
and the effect produced on my mind had nearly been my ruin forever.

My master seemed to be a very religious man, taking the sacrament, so called, regularly,
and praying every night in his family; unless his prayer book could not be found,
for he never prayed without it to my knowledge.
His example, however, made me sick of his religion:
for though I had but little religion myself,
I had some idea of what religious people ought to be.
Respecting religion, my opinions began to waver;
I even doubted whether there was any such thing;
and began to think that the convictions I had felt from my infancy,
were only the prejudices of education.
These convictions seemed now to be lost;
and for some months I do not remember to have felt them.
I became hardened, and was ready to conclude that there was no God.
The veneration I had felt for religious men, in my infancy, was entirely gone;
I now looked upon them in a very different manner.
My master`'s house was a place of great resort for the clergy;
and sometimes those who came from a distance lodged with him.
The observations I made on their conduct confirmed me in my atheistical opinions.
They diverted themselves in the evening, with cards and songs, and a few moments after,
introduced prayers and singing psalms to Almighty God.
Often did I say to myself, "`If there be a God, he is a pure Being,
and will not hear the prayers of polluted lips.`"

But he who hath in an abundant manner shown mercy to me, as will be seen in the sequel,
did not long suffer my mind to be perplexed with doubts; but, in a moment,
when my feet were on the brink of the bottomless pit, plucked me back.

To one woman, and to no other,
I told the nature of the difference which had happened two years before,
between my master and me.
By her means he heard of it, and though he knew it was true,
he sent for the town`'s whipper to correct me.
I was called in.
He never asked me whether I had told any such thing, but ordered me to strip.
My heart was ready to burst.
I would as freely have given up my life as have suffered such ignominy.
"`If,`" said I, "`there be a God,
be graciously pleased to look down on one of the most unhappy creatures,
and plead my cause;
for thou knowest that what I have related is the truth;`" and had
it not been for a principle more noble than he was capable of,
I would have told it to his wife.
Then fixing my eyes on the barbarous man, I said, "`Sir, if you have no pity on me,
yet for my father`'s sake spare me from this shame;
for he had heard several ways of my parents; and if you think I deserve such punishment,
do it yourself.`"
He took a turn over the room, and bade the whipper go about his business.
Thus I came off without a blow; but my character seemed to be lost.
Many reports of me were spread, which I bless God were not true.
I suffered so much cruelty that I could not bear it;
and was tempted to put an end to my miserable life.
I listened to the temptation, and for that purpose went into the garret to hang myself.
Now it was I felt convinced that there was a God.
As I entered the place, horror and trembling seized me;
and while I stood as one in amazement, I seemed to hear a voice saying,
"`There is a hell beyond the grave.`"
I was greatly astonished, and cried, "`God be merciful,
and enable me to bear whatsoever thou in thy providence,
shall bring or suffer to come upon me.`"
I then went downstairs, but let no one know what I had been about.

Soon after this I had a dream; and though some ridicule dreams,
this seemed very significant to me, and therefore I shall mention it.
I thought I heard a knocking at the door, by which, when I had opened it,
there stood a grave woman, holding in her right hand a lamp burning, who,
with a solid countenance, fixed her eye upon me and said, "`I am sent to tell thee,
that if thou wilt return to the Lord thy God, who created thee,
he will have mercy on thee, and thy lamp shall not be put out in obscurity.`"
Her lamp then flamed, in an extraordinary manner; she left me, and I awoke.

But, alas!
I did not give up to the "`heavenly vision,`" as I think I may call it.
I was nearly caught in another snare, of the most dangerous nature.
I was esteemed skilful at singing and dancing, in which I took great delight.
Once, falling in with a company of players, who were then in New York,
they took a great fancy, as they said, to me,
and invited me to become an actress amongst them.
They added, that they would find means to release me from my cruel servitude,
and I should live like a lady.
The proposal pleased me, and I took no small pains to qualify myself for them,
in reading their playbooks, even when I should have slept.
Yet, on reflection, I demurred at taking this new step,
when I came to consider what my father would think of it,
who had forgiven my disobedience in marrying, and had sent for me home,
earnestly desiring to see me again.
But my proud heart would not suffer me to return, in so mean a condition,
and I preferred bondage.
However, when I had served about three years, I bought out the remainder of my time,
and worked at my needle, by which I could maintain myself handsomely.
But, alas!
I was not sufficiently punished.
I released myself from one cruel servitude, and in the course of a few months,
entered into another for life,
by marrying a young man who fell in love with me for my dancing;
a poor motive for a man to choose a wife, or a woman a husband.
For my part, I was in love with nothing I saw in him; and it seems unaccountable to me,
that after refusing several offers, both in this country and Ireland,
I should at last marry one I did not esteem.

My husband was a school-master.
A few days after we were married, we went from New York to a place called Westerly,
in Rhode Island, where he had engaged to keep a school.
With respect to religion he was much like myself, without any; and when intoxicated,
would use the worst of oaths.
I do not mention this to expose him, but to show the effect it had on myself.
I saw myself ruined, as I thought, in being joined to a man I did not love,
and who was a pattern of no good to me.
We thus seemed hastening towards destruction, when I concluded,
if I was not forsaken of heaven, to alter my course of life.
To fix my affection on the Divine Being, and not to love my husband, seemed inconsistent.
I daily desired, with tears, that my affections might be directed in a right manner,
and can say, that in a little time, my love was sincere.
I resolved to do my duty to God,
and expecting I must come to the knowledge of it by the Scriptures,
I read these sacred writings with a determination to follow their directions.
The more I read, the more uneasy I grew, especially about baptism.
I had reason to believe I had been sprinkled in my infancy, because,
at the age of thirteen, I was confirmed by the bishop;
yet I could not discover a precedent for the practice.
In the course of reading, I came to the passage where it is said,
"`He that believes and is baptized,`" &c. Here I observed that belief,
of which I was not capable when sprinkled, went before baptism.
I conversed frequently with the Seventh-day Baptists that lived in the neighbourhood,
and at length thinking it a real duty,
was in the winter baptized by one of their teachers.
I did not strictly join with them,
though I began to think the seventh-day the true sabbath, and for a time kept it.
My husband did not oppose me, for he saw I grew more affectionate to him; and as yet,
I did not refuse to sing and dance when he asked me,
though this way of amusing myself did not yield me so much satisfaction as formerly.

My husband and I now formed the plan of going to England,
and for this purpose we went to Boston, where we found a vessel bound to Liverpool.
We agreed for our passage, and expected to sail in about two weeks; but in the mean time,
a gentleman hired the vessel to carry himself and his attendants to Fayal,
and take no other passengers.
There being no other ship near sailing, we for that time gave up our design,
though we continued at Boston several weeks.
My mind was still not satisfied with regard to religion.
I had reformed my conduct, so as to be accounted, by those who knew me, a sober woman;
yet I was not content, for I expected to find the sweets of such a change;
and though several thought me religious, I dared not to think so myself.
I conversed with people of all societies, as opportunity offered,
several of whom thought I was of their persuasion; however, I joined strictly with none,
but resolved never to leave off searching till I found the truth.
This was in the twenty-second year of my age.

While we were in Boston, I went one day to the Quakers`' meeting,
where I heard a woman Friend speak, at which I was a little surprised.
I had been told of women`'s preaching, but had never heard it before;
and I looked upon her with pity for her ignorance, and contempt for her practice;
saying to myself, "`I`'m sure you`'re a fool, and if ever I turn Quaker,
which will never be, I will not be a preacher.`"
Thus was my mind occupied while she was speaking.
When she had done, a man stood up, who I could better bear.
He spoke sound doctrine on good Joshua`'s resolution,
"`As for me and my house we will serve the Lord.`"
After sitting down and remaining silent awhile, he went to prayer,
which was attended with something so awful and affecting,
that it drew tears from my eyes.

After leaving Boston, my husband being given to rambling,
which was very disagreeable to me, we went to Rhode Island,
and from thence to the east end of Long Island, where he hired to keep a school.
This place was principally settled by Presbyterians,
and I soon became acquainted with the most religious among them.
My poverty was no bar to my reception with people of the best credit,
with whom I frequently conversed; but the more I became acquainted with them,
the less I liked their opinions.
Many temptations in the mean time, assaulted my unsettled mind.
Having been abroad one day, I perceived that the people in whose house we had a room,
had left some flax in an apartment through which I was to pass; at the sight of it,
I was tempted to steal some to make thread.
I went to it, and took a small bunch in my hand,
upon which I was smitten with such remorse that I laid it down again, saying,
"`Lord keep me from so vile an action.`"
But the temptation to steal became stronger than before,
and I took the bunch of flax into my room; when I came there, horror seized me,
and with tears I cried out, "`O, thou God of mercy,
enable me to abstain from this vile action.`"
I then took the flax back,
and felt that pleasure which is only known to those who have resisted temptation.

My husband having hired further up the island, we changed our residence,
and the nearest place of worship belonging to a congregation of the Church of England,
which, on the whole, I liked best, I attended it.

A fresh exercise, of a very peculiar kind, now came upon me.
It was in the second month: I thought myself sitting by a fire,
in company with several others, among whom was my husband;
when there arose a thunder gust, and a noise, loud as from a mighty trumpet,
pierced my ears with these words:
"`Oh eternity! eternity, the endless term of long eternity!`"
I was exceedingly astonished,
and while I was sitting as in a trance, I beheld a long roll,
written in black characters, hearing at the same time, a voice saying,
"`These are thy sins,`" and afterwards adding,
"`And the blood of Christ is not sufficient to wash them out.
This is shown thee that thou mayest confess thy damnation to be just,
and not in order that that thou shouldst be forgiven.`"
I sat speechless; at last I got up trembling and threw myself on the bed.
The company thought my indisposition proceeded from a fright occasioned by the thunder;
but it was of another kind.
For several months I was almost in a state of despair,
and if at any time I endeavoured to hope or lay hold of any gracious promise,
the tempter would insinuate that it was now too late; that the day of mercy was over;
and that I should only add to my sins by praying for pardon,
and provoke Divine vengeance to make of me a monument of wrath.
I was, as it were, already in torment.
I could not sleep, and ate but little.
I became extremely melancholy, and took no delight in any thing.
Had all the world been mine, I would have given it gladly for one glimpse of hope.

My husband was shocked to see me so changed.
I, who once used to divert him with singing and dancing, in which he greatly delighted,
could not, since I grew religious, do it any longer.
My singing was turned into mourning, and my dancing into lamentation.

My nights and days were one continued scene of sorrow;
but I let no one know the state of my mind.
In vain did my husband use all the means in his power to divert my melancholy.
The wound was too deep to be healed with any thing short of the balm of Gilead.
For fear of evil spirits I dared not, nor would my husband suffer me to go much alone;
and if I took up the Bible, he would take it from me, exclaiming, "`How you are altered;
you used to be agreeable company, but now I`'ve no comfort in you.`"
I endeavoured to bear all with patience,
expecting that I should soon have to bear more than man could inflict.

I went to the priest, to see if he could relieve me; but he was a stranger to my case.
He advised me to take the sacrament, and amuse myself with innocent diversions.
He also lent me a book of prayers, which he said were suited to my condition.
But all was to no purpose; as to the sacrament,
I thought myself in a very unfit state to receive it worthily: as for prayers,
it appeared to me that when I could pray acceptably,
I should be enabled to do it without form; and diversions were burdensome.
My husband, with a view to alleviate my grief,
persuaded me to go to the raising of a building, where much company was collected,
but it had a contrary effect.
An officer came to summons a jury to sit on the body of a man who had hanged himself;
on receiving which information,
a voice within me seemed to address me thus;-- "`Thou
shalt be the next to come to a like end;
for thou art not worthy to die a natural death.`"
For two months I was daily tempted to destroy myself,
often so strongly that I could scarcely resist.
Before I ventured to walk out alone, I left behind me every article which,
in an unguarded moment I might use for this purpose; fervently desiring,
at the same time, that God would preserve me from taking that life which he had given,
and which he would have made happy, if I had accepted the offers of his grace,
by regarding the convictions he had favoured me with from my youth.
During all this agony of mind, I could not shed a tear.
My heart was hardened, and my life miserable; but God in his infinite mercy,
delivered my soul from this thraldom.
One night, as I lay in bed, bemoaning my condition, I cried, "`Oh my God, I beseech thee,
in thy mercy, look down upon me for Christ`'s sake,
who hath promised that all manner of sins and blasphemies shall be forgiven.
Lord, if thou wilt be graciously pleased to extend this promise to me,
an unworthy creature, trembling before thee,
in all that thou shalt command I will obey thee.`"
In an instant my heart was tendered, and I was dissolved in a flood of tears.
I abhorred my past offences, and admired the mercies of my God.
I could now hope in Christ my Redeemer, and look upon him with an eye of faith.
I experienced what I believed when the priest lent me his book,
that when my prayers would be acceptable, I should not need a form, which I used no more.
I now took the sacrament, and can say I did it with reverence and fear.

Being thus released from my deep distress, I seemed like another creature,
and went often alone without fear.
Once, as I was abhorring myself, in great humility of mind,
I seemed to hear a gracious voice, full of love, say to me, "`I will never forsake thee,
only obey in what I shall make known unto thee.`"
I answered, "`My soul doth magnify the God of mercy.
If thou wilt dispense thy grace, the rest of my days shall be devoted to serve thee;
and if it be thy will that I should beg my bread,
I will submit with content to thy providence.`"

I now began to think of my relations in Pennsylvania, whom I had not yet seen.
My husband gave me liberty to visit them, and I obtained a certificate from the priest,
in order that, if I made any stay,
I might be received as a member of the church wherever I came.
My husband accompanied me to the Blazingstar ferry, saw me safely over, and then returned.
In my way, I fell from my horse, and for several days was unable to travel.
I abode at the house of an honest Dutchman, who, with his wife,
paid me the utmost attention, and would have no recompense for their trouble.
I left them with sentiments of deep gratitude for their extraordinary kindness,
and they charged me, if ever I came that way again, to lodge with them.
I mention this, because I shall have occasion to allude to it hereafter.

When I came to Trenton ferry,
I felt no small mortification on hearing that my relations were all Quakers,
and what was worst of all, that my aunt was a preacher.
I was exceedingly prejudiced against this people,
and often wondered how they could call themselves Christians.
I repented my coming, and was almost inclined to turn back;
yet as I was so far on my journey, I proceeded,
though I expected but little comfort from my visit.
How little was I aware that it would bring me to the knowledge of the Truth!

I went from Trenton to Philadelphia by water, and from thence to my uncle`'s on horseback.
My uncle was dead, and my aunt married again; yet,
both she and her husband received me in the kindest manner.
I had scarcely been three hours in the house,
before my opinion of these people began to alter.
I perceived a book lying upon the table, and being fond of reading, took it up;
my aunt observed me, and said, "`Cousin, that is a Quaker`'s book.`"
She saw I was not a Quaker, and supposed I would not like it.
I made her no answer, but queried with myself, what can these people write about?
I have heard that they deny the Scriptures,
and have no other Bible than George Fox`'s Journal -- denying, also,
all the holy ordinances.
But, before I had read two pages, my heart burned within me,
and for fear I should be seen, I went into the garden.
I sat down, and as the piece was short, read it before I returned,
though I was often obliged to stop to give vent to my tears.
The fulness of my heart produced the involuntary exclamation, "`O my God, must I,
if ever I come to the knowledge of thy Truth, be of this man`'s opinion,
who has sought thee as I have done; and must I join this people,
to whom a few hours ago I preferred the Papists.
O, thou God of my salvation, and of my life,
who hast abundantly manifested thy long suffering and tender mercy,
in redeeming me as from the lowest hell, I beseech thee to direct me in the right way,
and keep me from error; so will I perform my covenant,
and think nothing too near to part with for thy name`'s sake.
O, happy people, thus beloved of God!`"

After having collected myself, I washed my face,
that it might not be perceived I had been weeping.
In the night I got but little sleep;
the enemy of mankind haunted me with his insinuations,
suggesting that I was one of those who wavered, and was not steadfast in faith;
advancing several texts of Scripture against me, as that,
in the latter days there should be those who would deceive the very elect;
that of such were the people I was among, and that I was in danger of being deluded.
Warned in this manner,
(from the right source as I thought,) I resolved to be aware of those deceivers,
and for some weeks did not touch one of their books.
The next, day, being the first of the week, I was desirous of going to church,
which was distant about four miles; but being a stranger,
and having no one to go with me, I gave up all thoughts of that,
and as most of the family were going to meeting, I went there with them.

As we sat in silence, I looked over the meeting, and said to myself,
"`How like fools these people sit; how much better would it be to stay at home,
and read the Bible, or some good book, than to come here and go to sleep.`"
As for me I was very drowsy; and while asleep, had nearly fallen down.
This was the last time I ever fell asleep in a meeting.
I now began to be lifted up with spiritual pride, and to think myself better than they;
but this disposition of mind did not last long.
It may seem strange, that after living so long with one of this Society at Dublin,
I should yet be so much a stranger to them.
In answer, let it be considered that while I was there, I never read any of their books,
nor went to one meeting; besides, I had heard such accounts of them,
as made me think that, of all societies, they were the worst.
But he who knows the sincerity of the heart, looked on my weakness with pity;
I was permitted to see my error, and shown that these were the people I ought to join.

A few weeks afterwards, there was an afternoon meeting at my uncle`'s,
at which a minister named William Hammans was present.
I was highly prejudiced against him when he stood up, but I was soon humbled;
for he preached the Gospel with such power that I
was obliged to confess it was the truth.
But, though he was the instrument of assisting me out of many doubts,
my mind was not wholly freed from them.
The morning before this meeting I had been disputing with my uncle about baptism,
which was the subject handled by this minister,
who removed all my scruples beyond objection,
and yet I seemed loath to believe that the sermon
I had heard proceeded from divine revelation.
I accused my aunt and uncle of having spoken of me to the Friend;
but they cleared themselves, by telling me, that they had not seen him since my coming,
until he came into the meeting.
I then viewed him as the messenger of God to me, and laying aside my prejudices,
opened my heart to receive the truth; the beauty of which was shown to me,
with the glory of those who continued faithful to it.
I had also revealed to me the emptiness of all shadows and types, which,
though proper in their day, were now, by the coming of the Son of God, at an end,
and everlasting righteousness, which is a work in the heart,
was to be established in the room thereof.
I was permitted to see that all I had gone through was to prepare me for this day;
and that the time was near, when it would be required of me,
to go and declare to others what the God of mercy had done for my soul;
at which I was surprised, and desired to be excused,
lest I should bring dishonour to the Truth,
and cause his holy name to be evilly spoken of.
Of these things I let no one know.
I feared discovery, and did not even appear like a Friend.

I now hired to keep school, and hearing of a place for my husband, I wrote,
and desired him to come, though I did not let him know how it was with me.

I loved to be at meetings, but did not love to be seen going on week-days,
and therefore went to them from my school, through the woods.
Notwithstanding all my care, the neighbours, who were not Friends,
soon began to revile me with the name of Quaker; adding,
that they supposed I intended to be a fool, and turn preacher.
Thus did I receive the same censure, which, about a year before,
I had passed on one of the handmaids of the Lord in Boston.
I was so weak, that I could not bear the reproach, and in order to change their opinion,
went into greater excess of apparel than I had freedom to do,
even before I became acquainted with Friends.
In this condition I continued until my husband came, and then began the trial of my faith.

Before he reached me, he heard I was turned Quaker; at which he stamped, and said,
"`I had rather have heard she was dead, well as I love her; for, if it be so,
all my comfort is gone.`"
After an absence of four months, he came to me, and I got up and said to him, "`My dear,
I am glad to see thee.`"
At this, he flew into a great rage, exclaiming, "`The devil thee, thee, thee,
don`'t thee me.`"
I endeavoured by every mild means to pacify him;
and at length got him fit to speak to my relations.
As soon after this as we were alone, he said to me,
"`And so I see your Quaker relations have made you one;`" I replied, that they had not,
which was true, I never told them how it was with me.
He said he would not stay amongst them; and having found a place to his mind, hired,
and came directly back to fetch me, walking, in one afternoon,
thirty miles to keep me from meeting the next day, which was first-day.
He took me, after resting this day, to the place where he had hired,
and to lodgings he had engaged at the house of a churchwarden.
This man was a bitter enemy of Friends,
and did all he could to irritate my husband against them.

Though I did not appear like a Friend, they all believed me to be one.
When my husband and he used to be making their diversions and reviling, I sat in silence,
though now and then an involuntary sigh broke from me; at which he would say, "`There,
did not I tell you your wife was a Quaker, and she will become a preacher.`"
On such an occasion as this, my husband once came up to me in a great rage,
and shaking his hand over me, said, "`You had better be hanged in that day.`"
I was seized with horror, and again plunged into despair,
which continued nearly three months.
I was afraid that, by denying the Lord, the heavens would be shut against me.
I walked much alone in the woods, and there, where no eye saw, nor ear heard me,
lamented my miserable condition.
Often have I wandered, from morning till night, without food.
I was brought so low that my life became a burden to me, and the devil seemed to vaunt,
that though the sins of my youth were forgiven me,
yet now I had committed an unpardonable sin, and hell would inevitably be my portion,
and my torments greater than if I had hanged myself at first.

In the night, under this painful distress of mind, I could not sleep,
and if my husband perceived me weeping, he would revile me for it.
At length, when he and his friend thought themselves too weak to overset me,
he went to the priest at Chester, to inquire what he could do with me.
This man knew I was a member of the church, for I had shown him my certificate.
His advice was, to take me out of Pennsylvania,
and settle in some place where there were no Quakers.
My husband replied, he did not care where we went,
if he could but restore me to my natural liveliness of temper.
As for me, I had no resolution to oppose their proposals, nor much cared where I went.
I seemed to have nothing to hope for.
I daily expected to be made a victim of Divine wrath,
and was possessed with the idea that this would be by thunder.

When the time of removal came, I was not permitted to bid my relations farewell; and,
as my husband was poor, and kept no horse, I was obliged to travel on foot.
We came to Wilmington, fifteen miles, and from thence to Philadelphia by water.
Here we stopped at a tavern, where I became the spectacle and discourse of the company.
My husband told them his wife had become a Quaker, and he designed, if possible,
to find out a place where there were none.
I thought I was once in a condition to deserve that name, but now it is over with me.
O that I might, from a true hope, once more have an opportunity to confess the truth;
though I was sure of all manner of cruelties, I would not regard them.
Such were my concerns, while he was entertaining the company with my story,
in which he told them that I had been a good dancer,
but now he could get me neither to dance nor sing.
One of the company then started up, and said, "`I`'ll fetch a fiddle,
and we`'ll have a good dance;`" a proposal with which my husband was pleased.
When the fiddle was brought, my husband came and said to me, "`My dear,
shake off that gloom, and let us have a civil dance; you would, now and then,
when you were a good churchwoman, and that`'s better than a stiff Quaker.`"
I had taken up the resolution not to comply with his request,
whatever might be the consequence; this I let him know, though I durst say but little,
for fear of his choleric temper.

He pulled me round the room, till the tears fell from my eyes,
at the sight of which the musician stopped, and said "`I`'ll play no more;
let your wife alone.`"
A person in company, who came from Freehold, in East Jersey, said,
"`I see your wife`'s a Quaker, but,
if you`'ll take my advice you need not go so far as you intend; come and live with us;
we`'ll soon cure her of her Quakerism,
and we want a school-master and school-mistress too.`"
He consented, and a happy turn it was for me, as will shortly be seen.
The answer of peace was afforded me, for refusing to dance;
I rejoiced more than if I had been made mistress of much riches, and with tears, prayed,
"`Lord, I dread to ask, and yet without thy gracious pardon, I am miserable.
I therefore fall down before thy throne, imploring mercy at thy hand.
O Lord, once more, I beseech thee, try my obedience, and then,
in whatsoever thou commandest, I will obey thee,
and not fear to confess thee before men.`"
My cries were heard, and it was shown to me,
that he delights not in the death of a sinner.
My soul was again set at liberty, and I could praise him.

In our way to Freehold, we visited the kind Dutchman,
whom I have mentioned in a former part of this narrative.
He made us welcome, and invited us to pass a day or two with him.
During our stay, we went to a large meeting of Presbyterians, held not only for worship,
but business; and the trial of one of their priests,
who had been charged with drunkenness, was to come on.
I perceived such great divisions among the people,
respecting who should be their shepherd, that I pitied them.
Some insisted on having the old offender restored;
others wished to have a young man they had had on trial for some weeks; others, again,
were for sending to New England for a minister.
In reply, one who addressed himself to the chief speaker observed, "`Sir,
when we have been at the expense, which will not be trifling,
of fetching this gentleman from New England, perhaps he`'ll not stay with us.`"
"`Don`'t you know how to make him stay?`"
said another.
"`No sir.`"
"`I`'ll tell you; give him a large salary, and I`'ll engage he`'ll stay.`"
I listened attentively to the debate, and it plainly appeared to me,
that these mercenary preachers were actuated by one motive, which was,
not the regard for souls, but the love of money.
One of these men, called a reverend divine, whom these people almost adored, had,
to my knowledge, left his flock in Long Island, and removed to Philadelphia,
where he could get more money.
I have myself heard some on the island say that they had
almost impoverished themselves in order to keep him;
but, being unable to equal what he was offered at Philadelphia, he left them.
Surely these are the shepherds who regard the fleece more than the flock,
and in whose mouths are lies, when they say that they are the ambassadors of Christ,
whose command it is, "`Freely ye have received, freely give.`"

In our way to Freehold, as we came to Stony Brook,
my husband turned towards me and tauntingly said, "`Here`'s one of Satan`'s synagogues,
don`'t you long to be in it; I hope to see you cured of your new religion.`"
A little further on we came to a large run of water, over which there was no bridge,
and being strangers we knew no way to avoid passing through it.
He carried over our clothes, which we had in bundles; and taking off my shoes,
I walked through in my stockings.
It was in the twelfth month;
the weather was very cold and a fall of snow lay on the ground.
It was the concern of my heart,
that the Lord would sanctify all my afflictions to me and give me patience to bear them.
After walking nearly a mile we came to a house, which proved to be a sort of tavern.
My husband called for some spirituous liquors, and I got some weakened cider mulled,
which rendered me extremely sick; so that after we were a little past the house,
being too faint to proceed I fell down.
"`What`'s the matter now?`"
said my husband, "`what, are you drunk?
Where`'s your religion now?`"
He knew I was not drunk, and at that time I believe he pitied me,
although he spoke in this manner.
After I was a little recovered, we went on and came to another tavern, where we lodged.
The next day as we journeyed, a young man driving an empty cart, overtook us.
We asked him to let us ride, and he readily granted the request.
I had known the time when I would not have been seen in a cart,
but my proud heart was humbled, and I did not now regard the look of it.
This cart belonged to a man in Shrewsbury,
and was to go through the place of our destination.
We soon had the care of the team to ourselves, through a failure of the driver,
and arrived with it at Freehold.
My husband would have had me stay here, while he went to see the team safe home;
I told him, no; since he had led me through the country like a vagabond,
I would not stay behind him.
We therefore went together, and lodged that night at the house of the owner of the cart.
The next day on our return to Freehold, we met a man who said to my husband, "`Sir,
are you a schoolmaster?`"
He answered, "`Yes.`"
"`I am come,`" replied the stranger, "`to tell you of two new school-houses,
two miles apart, at each of which a master is wanted.`"
How this person came to hear of us, who arrived but the night before, I never knew.
I was glad he was not a Quaker, lest it should have been thought a plot by my husband,
to whom I turned and said,-- "`My dear, look on me with pity,
if thou hast any affection left for me, which I hope thou hast,
for I am not conscious of having done any thing to alienate it.
Here is an opportunity to settle us both, and I am willing to do all in my power,
towards getting an honest livelihood.`"
After a short pause, he consented to go with the young man.
In our way, we came to the house of a worthy Friend, who was a preacher,
though we did not know it.
I was surprised to see the people so kind to us.
We had not been long in the house, till we were invited to lodge there for the night,
being the last of the week.

My husband accepted the invitation, saying, "`My wife has had a tedious travel,
and I pity her.`"
These kind expressions affected me, for I heard them very seldom.
The Friend`'s kindness could not proceed from my appearing like a Quaker,
because I had not yet altered my dress.
The woman of the house, after we had concluded to stay, fixed her eyes upon me, and said,
"`I believe thou hast met with a deal of trouble,`" to which I made but little answer.
My husband observing they were of that sort of people
whom he had so much endeavoured to shun,
gave us no opportunity for discourse that night; but the next morning,
I let my friend know a little of my situation.

When meeting time came I longed to go, but dared not to ask my husband`'s leave.
As the Friends were getting ready themselves, they asked him if he would accompany them,
observing, that they knew those who were to be his employers,
and if they were at meeting, would speak to them.
He consented.
The woman Friend then said,
"`And wilt thou let thy wife go too;`" which request he denied;
but she answered his objections so prudently that he could not be angry,
and at last consented.
I went with joy, and a heavenly meeting it was.
My spirit did rejoice in the God of my salvation.
May I ever in humility, preserve the remembrance of his tender mercies to me.

By the end of the week, we got settled in our new situation.
We took a room in a Friend`'s house, one mile from each school,
and eight from the meetinghouse.
I now deemed it proper to let my husband see I was determined to join with Friends.
When first-day came, I directed myself to him in this manner; "`My dear,
art thou willing to let me go to meeting?`"
He flew into a rage, and replied, "`No you shan`'t.`" Speaking firmly, I told him,
"`That as a dutiful wife, I was ready to obey all his lawful commands;
but when they imposed upon my conscience, I could not obey him.
I had already wronged myself, in having done it too long; and though he was near to me,
and as a wife ought, I loved him, yet God, who was nearer than all the world to me,
had made me sensible that this was the way in which I ought to go.
I added, that this was no small cross to my own will; but I had given up my heart,
and I trusted that He who called for it would enable me for the remainder of my life,
to keep it steadily devoted to his service; and I hoped I should not on this account,
make the worse wife.`"
I spoke however, to no purpose;--he continued inflexible.
I had now put my hand to the plough, and resolved not to draw back;
I therefore went without leave.
I expected he would immediately follow and force me back, but he did not.
I called at the house of one of the neighbours, and getting a girl to show me the way,
I went on rejoicing and praising God in my heart.

Thus for some time, I had to go eight miles on foot to meeting,
which I never thought hard.
My husband had a horse, but he would not suffer me to ride on it;
nor when my shoes were worn out, would he let me have a new pair;
but though he hoped on this account to keep me from meeting,
it did not hinder me:--I have tied them round with strings to keep them on.

Finding that all the means he had yet used could not alter my resolutions,
he several times struck me severe blows.
I endeavoured to bear all with patience,
believing that the time would come when he would see I was in the right.
Once he came up to me, took out his penknife and said,
"`If you offer to go to meeting tomorrow, with this knife I`'ll cripple you,
for you shall not be a Quaker.`"
I made him no answer.
In the morning I set out as usual; and he did not attempt to harm me.--

Having despaired of recovering me himself, he fled for help to the priest,
whom he told that I had been a very religious woman, in the way of the Church of England;
of which I was a member and had a good certificate from Long Island;
that I was now bewitched and had turned Quaker, which almost broke his heart;
and therefore, he desired that as he was one who had the care of souls,
he would come and pay me a visit and use his endeavours to reclaim me,
which he hoped by the blessing of God, would be done.
The priest consented and fixed the time for his coming, which was that day two weeks,
as he said he could not come sooner.
My husband came home extremely pleased, and told me of it.
I replied with a smile,
I trusted I should be enabled to give a reason for the hope within me;
yet I believed at the same time, that the priest would never trouble himself about me,
which proved to be the case.
Before the day he appointed came, it was required of me in a more public manner,
to confess to the world what I was.
I felt myself called to give up to prayer in meeting.
I trembled, and would freely have given up my life to be excused.
What rendered the required service harder was,
that I was not yet taken under the care of Friends;
and was kept from requesting to be so, for fear I should bring a scandal on the Society.
I begged to be excused till I had joined, and then I would give up freely.
The answer was, "`I am a covenant-keeping God,
and the word that I spake to thee when I found thee in distress,
even that I would never forsake thee if thou wouldst
be obedient to what I should make known unto thee,
I will assuredly make good.
If thou refusest, my spirit shall not always strive.
Fear not, I will make way for thee through all thy difficulties,
which shall be many for my name`'s sake; but be faithful,
and I will give thee a crown of life.`"
To this language I answered, "`Thy will, O God, be done; I am in thy hand,
do with me according to thy word;`" and I then prayed.

This day as usual, I had gone to meeting on foot.
While my husband, as he afterwards told me, was lying on the bed,
these words crossed his mind: "`Lord, where shall I fly to shun thee,`" etc.;
upon which he arose, and seeing it rain, got the horse and set off to fetch me,
arriving just as the meeting broke up.
I got on horseback as quickly as possible, lest he should hear I had been speaking;
he did hear of it nevertheless, and as soon as we were in the woods, began with saying,
"`Why do you mean thus to make my life unhappy?
What, could you not be a Quaker, without turning fool in this manner?`"
I answered in tears, "`My dear, look on me with pity if thou hast any;
canst thou think that I, in the bloom of my days,
would bear all that thou knowest of and much that thou knowest not of,
if I did not feel it my duty?`"
These words touched him, and he said, "`Well, I`'ll e`'en give you up;
I see it won`'t avail to strive; if it be of God I cannot overthrow it;
and if of yourself, it will soon fall.`"
I saw the tears stand in his eyes, at which I was overcome with joy,
and began already to reap the fruits of my obedience.
But my trials were not yet over.
The time appointed for the priest to visit me arrived, but no priest appeared.
My husband went to fetch him, but he refused, saying he was busy,
which so displeased my husband that he never went to hear him again,
and for some time went to no place of worship.

My faith was now assaulted in another way so strongly,
that all my former trials were but trifling to it.
This exercise came upon me unexpectedly, by hearing a woman speak of a book she had read,
in which it was asserted that Christ was not the Son of God.
A voice within me seemed to answer, "`No more is he, it`'s all a fancy,
and the contrivance of men.`"

Thus again was I filled with inexpressible trouble, which continued three weeks;
and again did I seek desolate places, where I might make my moan.
I have laid whole nights without sleep.
I thought myself deserted of God, but did not let go my trust in him.
I kept alive a hope, that He who had delivered me as it were out of the paw of the bear,
and the jaws of the lion, would in his own good time,
deliver me from this temptation also.
This was at length my experience; and I found the truth of his words,
that all things shall work together for the good of those who love and fear him.
My present exercises were to prepare me for further services in his cause;
and it is necessary for his ministers to experience many baptisms,
that they may thereby be more able to speak to the conditions of others.

This happened just after my first appearance as a minister,
and Friends had not been to talk with me.
They did not well know what to do until I appeared again, which was not for some time,
when the Monthly Meeting appointed four Friends to pay me a visit.
They left me well satisfied with the conference, and I joined the Society.
My husband still went to no place of worship.
One day he said to me, "`I would go to meeting, only I`'m afraid I shall hear your clack,
which I cannot bear.`"
I used no persuasions.
When meeting-time came he got the horse, took me behind him and went.
For several months, if he saw me offer to rise he went out;
till one day I rose before he was aware, and then as he afterwards owned,
he was ashamed to do it.

From this time he left off the practice, and never hindered me from going to meeting.
Though he did not take up the cross, yet his judgment was convinced;
and sometimes melting into tears, he would say to me, "`My dear,
I have seen the beauty there is in the Truth, and that thou hast followed the right way,
in which I pray God to preserve thee.`"
I told him that I hoped He who had given me strength would also favour him.
"`O,`"said he, "`I cannot bear the reproach thou dost, to be called turn-coat,
and become a laughing-stock to the world; but I`'ll no longer hinder thee.`"
This I considered a favour, and a little hope remained that my prayers on his account,
would be heard.

We lived in a small house by ourselves, which, though mean,
and though we had little to put in it, our bed being no better than chaff,
I was truly content.
The only desires I had were for my own preservation,
and to be blessed with the reformation of my husband.
He was connected with a set of men whom he feared would make game of him,
which indeed they already did; asking him when he designed to commence preacher,
for they saw he intended to turn Quaker,
and seemed to love his wife better since she became one than before.
They used to come to our house, and provoked him to sit up and drink with them,
sometimes till near day, while I have been sorrowing in a stable.
Once as I sat in this condition, I heard him say to his company,
"`I can`'t bear any longer to afflict my poor wife in this manner;
for whatever you may think of her, I do believe she`'s a good woman.`"
He then came to me and said, "`Come in my dear, God has given thee a deal of patience:
I`'ll put an end to this practice.`"
This was the last time they sat up at night.

My husband now thought that if he was in any place where
it was not known he had been so bitter against Friends,
he could do better.
I objected to this, fearing it would not be for his benefit.
Frequently in a broken and affectionate manner, he condemned his ill usage of me.
I answered that I hoped it had been for my good,
and therefore desired he would not be afflicted on that account.
According to the measure of grace received, I did what I could,
both by example and precept, for his good.
My advice was to stay where he was,
as I was afraid he would grow weaker in his good resolutions, if he removed.

All I could say would not avail.
Hearing of a place at Bordentown he went thither, but was not suited.
He next removed to Mount Holly, where he settled.
We had each of us a good school; we soon got our house pretty well furnished,
and might have done very well.
Nothing seemed wanting to complete my happiness, except the reformation of my husband,
which I had much reason to fear that I should not soon see.
It fell out according to my fears.
He addicted himself much to drinking, and grew worse than before.
Sorrow was again my lot, I prayed for patience to bear my afflictions,
and to submit to the dispensations of Providence.
I murmured not;
nor do I recollect that I ever uttered any harsh expressions except on one occasion.

My husband coming home a little intoxicated, a state in which he was very fractious,
and finding me at work by a candle, he put it out, fetching me at the same time,
a box on the ear, and saying, "`You don`'t earn your light.`"
At this unkind usage, which I had not been used to for the last two years,
I was somewhat angry, and said, "`Thou art a vile man.`"
He struck me again; but my anger had cooled,
and I received the blow without so much as a word in return.
This also displeased him, and he went on in a distracted like manner,
uttering such expressions of despair as, he believed he was predestined to damnation,
and he did not care how soon God struck him dead.
I said very little, till at length in the bitterness of my soul,
I broke out into these expressions: "`Lord, look down on my afflictions,
and deliver me by some means or other.`"
My prayer was granted, but in such a manner that I thought it would have killed me.
He went to Burlington, where he got drunk,
and enlisted to go as a common soldier to Cuba, in the year 1740.
I had drunk many bitter cups, but this seemed the bitterest of them all.
I blamed myself for making such a request, which I was afraid had displeased God,
who had in displeasure, granted it for my punishment.

I have since had cause to believe that he was benefitted by his rash act, as in the army,
he did what he could not at home; -- he suffered for the testimony of Truth.
When they came to prepare for an engagement, he refused to fight;
he was whipped and brought before the general,
who asked him why he enlisted if he would not fight.
"`I did it,`" said he, "`in a drunken frolic, when the devil had the better of me;
but now my judgment is convinced I ought not to fight, neither will I, whatever I suffer.
I have but one life, and you may take that if you please, for I`'ll never take up arms.`"
He adhered to this resolution.
By their cruel usage of him in consequence,
he was so much disabled that the general sent him to Chelsea Hospital, near London.
Within nine months afterwards he died at this place, and I hope made a good end.

I never thought him the worst of men.
If he had suffered religion to have its perfect work,
I should have been happy in the lowest situation of life.
I have had cause to bless God, for enabling me in the station of a wife, to do my duty,
and now that I am a widow, I submit to his will.
May I still be preserved by the arm of Divine Power;
and never forget the tender mercies of my God,
the remembrance of which often boweth my soul in humility before his throne.
"`Lord! what was I, that thou shouldst reveal to my soul the knowledge of thy truth,
and have done so much for one who deserved thy displeasure?
Mayest thou, O God, be glorified and I abased.
It is thy own works that praise thee; and of a truth,
to the humble soul thou makest every bitter thing sweet.`"

The foregoing account was written by Elizabeth Ashbridge:
the few particulars which follow,
were written by her last husband and sent along with it.

Her husband had been gone two or three years before she heard of his death.
He left her nearly eighty pounds in debt, which by law she was not obliged to pay,
for want of effects; yet as several creditors complained,
and said they would not have trusted him if it had not been for her sake,
she engaged to satisfy them all as fast as she could.
She settled steadily to the business of school-keeping, with which and her needle,
she maintained herself handsomely.
She gradually paid off the above debts,
and had nearly discharged them all during her widowhood,
though she travelled much in the mean time, as a minister.

In the ninth month, 1746, we were married at Burlington, West Jersey.
The company of each other was dear and delightful, but the time came when we must part.
Sufficiently convinced that her Lord and Master called for her services abroad,
my heart was willing to give up the darling object of its love.
Though it has pleased the Divine Will to remove her
without indulging my longing desire to see her again,
yet fully satisfied that she is called from the troubles of time to a happy eternity,
I am resigned and enjoy a grateful composure of mind.
She left home the 11th of the fifth month, 1753, and died in Ireland,
the 16th of the fifth month, 1755.

[.signed-section-signature]
Aaron Ashbridge.
