[short="Testimony from the National Meeting of Ireland"]
== Abstract of a Testimony from, the National Meeting of Ireland, held in Dublin, concerning Elizabeth Ashbridge.

In the year 1753, apprehending it required of her to visit the meetings of Friends,
in England and Ireland, she left her habitation with the consent of her husband,
and the unity and approbation of Friends as appears by her certificate,
and performed a religious visit to many meetings in this nation,
to the general satisfaction of Friends;
wherein she endured so much bodily hardship in travelling
and underwent so much spiritual exercise,
that she fell dangerously ill at the city of Cork.

After recovering strength so as to be able to proceed on her journey,
she left Cork and came to Waterford, to the house of our friend John Hutchinson,
where she remained very much indisposed for the most part of fourteen weeks;
and in that interval, was at the province meeting at Clonmel,
where she had extraordinary service.
From there she got to the county of Carlow, to the house of our friend Robert Lecky;
while there, some expressions which she uttered in an affecting manner,
were taken down in writing, and are as follow.

The 7th of the fifth month, 1755, being sorely afflicted with pain of body,
she expressed her fear of not being patient enough under it,
but several times desired she might, saying, "`O dearest goodness,
grant me patience till my change come, and then do not forsake me, Lord of my life.`"
Speaking of what she had suffered, she observed,
"`words could not express nor thoughts conceive,
what she had gone through during the past seven months;
for what cause the Lord only knew.
Although it had been so with her, yet she would not have any to be discouraged,
for her master was a good master, and she did not grudge suffering for him.
Though he chastises his children, it is for some good end;
sometimes for their own and sometimes for the good of others.`"
She said, "`she did not repent coming into this nation,
being satisfied she was in her place,
and that it was the requiring of Him who had supported her to a miracle:
and now it looked as if she and her companion were sent to lay
down their lives in the cause of Truth,`" her companion Sarah Worral
having departed this life at Cork a short time before;
"`that many faithful servants had been sufferers in this land,
and as they were not the first, so she thought they would not be the last.`"
Those who had put their hands to the plough, she desired might go on with courage,
and said, "`God was on their side;
and that it was happy for those who remembered their Creator in their youth.`"

Another time when in extreme pain, she cried out, "`Lord,
look down upon me,`" and begged, "`that patience, her old companion,
might not leave her;`" and said, "`although pain of body was her portion at present,
through the mercies of a gracious God her mind was pretty easy.`"
Sometimes she feared she was not quite fitted for
that glorious mansion which she aimed at,
and into which nothing that is unholy can enter;
yet had a hope it was not in wrath she was chastised,
as she felt the touches of Divine love to her soul; and said, "`she loved the Truth,
and those that loved it were precious to her life, whether relations or others;
and that she had sought it from her youth,
and was thankful for being preserved so as not to bring a blemish on it,
since she made profession thereof, but had done what she could for it.`"

A Friend taking leave of her, she told him "`Whether he heard of her life or death,
she hoped it would be well.`"
Some Friends being with her she said something of the singularity of her trials,
but that "`the hand that permitted them,
had an indisputable right;`" to which she seemed resigned whether in life or death,
hoping it would be well.
She said, "`she loved the Truth,
and it had been her support;`" and desired those who had begun to walk in it,
"`to keep close to it, and it would never leave them.`"

She seemed thankful that the beauty of this world and the enjoyments of it,
were stained in her view, and she made willing to give up all;
the hardest to part with was her dear husband, from whom she was so far separated;
but even that was made easier than she could expect.
Being wished a good night`'s rest; she said "`she did not expect to be free from pain,
but that every night the Lord sent, was good; and though uneasy,
hoped they all would be good nights,
and when once the gulph was passed she should have rest.`"

She said, "`she endeavoured to live without a will;
and hoped she had borne her afflictions with a degree of Christian fortitude.`"
Being in great pain, and asked whether she would be settled?
she said "`None could settle her but one; and in his own time, she hoped he would.`"
Then cried out, "`Dearest Lord, though you slay me, I will die at your feet;
for I have loved you more than life.`"
She gratefully acknowledged the care and tenderness shown to her,
and counted it a high favour that the hearts of her friends
were opened to receive and sympathize with her.
She spoke of the exercises of mind she went through before her convincement,
and of the time she got relief from great distress
and was enabled to make covenant with the Lord;
"`which time she hoped she should never forget,
being desirous often to return to Bethel and to remember the time of her espousals.`"
She acknowledged the advantage there was "`in being deeply tried,
and that it was the way to be enabled to speak comfortably to others.`"

Having grown weaker for several days, she departed this life in a quiet frame,
the 16th of the fifth month, 1755, and on the 19th her corpse,
accompanied by many Friends, was buried in Friends`' burying-ground at Ballybrumhill,
where several testimonies were borne to the Truth.

[.blurb]
=== To this account of her last sickness and death, the National Meeting of Ireland adds this testimony:

"`She was a woman of an excellent natural understanding; in her conduct cheerful,
yet grave and instructive; she felt the afflictions of others with a tender sympathy,
and bore her own with patience and resignation.

"`As a minister, she was deep in travail, clear in her openings,
plain and pertinent in her expressions, solid and awful in her deportment,
and attended with that baptizing power, which is the evidence of a living ministry;
and which so evidently attended her in the last testimony she bore in a public meeting,
in great bodily weakness,
that most or all present were reached and deeply affected thereby,
and a young woman was at that time, convinced of the Truth;
which was as a seal to the finishing of her service in the work of the ministry;
and in which, being so owned to the last,
we have no doubt but she now receives the reward of the faithful servant,
and is entered into the joy of her Lord.`"
