== The Life of Elizabeth Ashbridge.

As my life has been attended with many uncommon occurrences,
I have thought it proper to make some remarks on the dealings of Divine Goodness with me.
I have often had cause with David to say,
"`It is good for me that I have been afflicted;`"^
footnote:[Ps. 119:71]
and I most earnestly desire that they who read the following lines may take warning,
and shun the evils into which I have been drawn.

I was born at Middlewich, in Cheshire, in the year 1713, of honest parents,
named Thomas and Mary Sampson.
My father bore a good character, but he was not so strictly religious as my mother,
who was a pattern of virtue to me.
I was my father`'s only child, but my mother had a son and a daughter by a former husband.
Soon after I was born, my father went to sea,
and following his profession (which was that of a surgeon) made many long voyages.
He continued in his sea-faring course of life until I was twelve years old,
so that the care of the early part of my education devolved upon my mother;
and she discharged her duty in endeavoring to imbue my mind with the principles of virtue.

I have had reason to be thankful that I was blessed with such a parent;
her good advice and counsel to me have been as "`bread cast
upon the waters`" which returned after many days.^
footnote:[Ecclesiastes 11:1]
She was an instructive example to all who knew her, and was generally beloved by all.
But alas,
as soon as the time came when she might reasonably expect
some benefit from her labors and find comfort in me,
I deserted her.

In my childhood I had a deep regard for religion and religious people,
particularly for ministers, all of whom I believed to be good men and beloved of God,
which I earnestly wished to be my own case.
I also had a great tenderness for the poor,
remembering reading that they were "`beloved of the Lord.`"
This I supposed to mean such as were poor in temporal things,
and so I often visited them in their cottages,
and used to think they were better off than myself.
And if I had money, or anything suitable for a gift, I bestowed it on them,
recollecting that they who gave to the poor lent unto the Lord.
I admonished those who made shallow pretenses to religion; and when I heard people swear,
I was troubled; for my mother told me that if I used any naughty words,
God would not love me.

I observed that there were several different religious societies.
I often thought of this and wept,
with desires that I might be directed to the one which would be best for me to join.
In this frame of mind I passed my younger years.
I was sometimes guilty of the faults common among children,
but was always sorry for whatever I had done amiss; and,
until I was fourteen years of age, I was as innocent as most children.
But about this time,
my sorrows (which have continued for the greatest part of my life) began,
by my giving way to a foolish passion in setting my affections on a young man, who,
without the permission of my parents, courted me till I consented to marry him;
after which--with sorrow of heart I relate it--I
allowed myself to be carried off in the night.
We were married.
My parents made all possible search for me as soon as I was missing, but it was in vain.

This hasty act plunged me into much sorrow.
I was quickly smitten with remorse for thus leaving my parents,
whose right it was to be consulted on such an occasion.
But I was soon chastised for my disobedience, and convinced of my error;
for in only five months time, I was stripped of the darling of my heart,
and left a young and disconsolate widow.
I was now without a home.
My husband had derived his livelihood from his trade,
which was that of a stocking weaver; and my father was so displeased at my conduct,
that he would do nothing to help me.
My dear mother had some compassion for me, and placed me among her neighbors.
Afterwards, by her advice, I went to live with a relation of hers at Dublin.
We hoped that my absence would soften my father`'s rigor; but he continued inflexible.
He would not send for me to return, and I dared not go back unless he did.

The relation I went to reside with was one of the people called Quakers.
His habits were so very different from what I had been accustomed to,
that the visit proved disagreeable to me.
I had been brought up in the way of the Church of England, and though, as I have said,
I had a religious upbringing, I was yet allowed to sing and dance,
which my cousin would not permit.
The great vivacity of my natural disposition would not then allow
me to give way to the gloomy sense of sorrow and conviction,
and therefore my present restraints had a wrong effect,
for I became more wild and airy than ever.
My cousin often reproved me,
but I then thought his conduct stemmed from a desire to appear peculiar,
and I would not be controlled.
Having a distant relation in the West of Ireland, I went to live with him.

Here I enjoyed all the liberty I could desire;
for that which rendered me disagreeable to my other kinsman,
was quite pleasing to this one.
Between these two relations I spent the next three years and three months.

While I was in Ireland,
I contracted an intimate acquaintance with a widow and her daughter,
who were Roman Catholics.
We conversed very frequently about religion, each of us defending our peculiar tenets;
and, though I was much given to levity, our discussions often made me thoughtful.
The old woman told me of such mighty miracles done by their priests,
that I began to be shaken in my own beliefs; and thought, if these things were so,
they must truly be the apostles`' successors.
She perceived the state of my mind, and one day exclaimed with rapture, "`Oh,
if I can be the happy instrument of converting you to the holy Catholic faith,
all the sins I ever committed will be forgiven!`"
Sometimes I attended her place of worship, but none of my relations knew my motive.
The matter went so far, that a priest came to converse with me.
Being young, and my judgment weak, I was ready to believe what he said;
and yet I resolved not to blindly adopt their creed.
I thought that if their articles of faith were sound,
they would not be against my knowing what they were; and, therefore,
the next time I saw the priest,
I told him that I had some intention of becoming one of his flock,
but wished first to know what I must agree to.
He answered that I must first confess my sins to him;
and gave me until the next day to consider them.
I was not averse to this,
conscious of having done nothing for which anyone could harm me;
and thinking that if what he had said was true, the confession would be for my good.
When he came again, I told him all that I could remember; which, for my part,
I thought was bad enough;
but he said he considered me the most innocent creature
that had ever made confession to him.
When I had finished, he took a book and read from it,
and told me that if I were to join them, I must swear to believe these things.
I shall not trouble the reader with the recital of its ridiculous contents.
What principally made me hesitate in my new intention
was that I was to swear that the Pretender,^
footnote:[James Francis Edward Stuart, nicknamed the Old Pretender,
was the Catholic son of the deposed King James 2.,
who claimed to be the rightful heir of the English and Scottish thrones,
and made several attempts to take the crown from William and Mary,
and later from Queen Anne.]
King James`'s son, was the true heir of the crown of England;
and that all who died outside the Romish church would be damned.
These doctrines startled me.
I hesitated, and requested time to take them into consideration; but,
before I saw the priest again,
a change of circumstances freed me from the necessity of giving him an answer.

My father still keeping me at such a distance,
I thought myself entirely excluded from his affections,
and therefore resolved not to return home.
I became acquainted with a gentlewoman,
lately arrived from Pennsylvania who was intending to return;
and as I had an uncle (my mother`'s brother) in that province,
I soon agreed with her for my passage.
I was ignorant of the nature of an indenture,^
footnote:[Indentured servitude is a form of labor in which a person
signs a binding contract to work without salary for a specific
number of years in exchange for the payment of a debt,
or the cost of transportation over seas.]
and allowed myself to be bound.
This was done privately, that it might not be found out.
As soon as I signed the contract, she invited me to see the vessel in which I was to sail.
I readily consented and we went on board, where there was another young woman, who,
as I afterwards found,
was of a respectable family and had been brought there in the same way as myself.
I was pleased with the thought that I should have
such an agreeable companion in my voyage.
While we were busy conversing, my conductor went on shore, and when I wished to go,
I was not permitted.
I then realized I had been kidnapped.
I was kept a prisoner in the ship for three weeks,
at the end of which time my companion was found by some of her friends,
who fetched her away; and by her information, my friends sent the water bailiff,^
footnote:[A law-enforcement officer responsible for policing bodies of water.]
who took me on shore.
I was kept in custody for two weeks, but at length found means to get away.

Nevertheless,
I was so filled with the thoughts of going to America that I would not give up the design;
and finding the captain, I inquired when he sailed; he told me, and I went on board.
There were in the ship, sixty Irish servants and several English passengers.
The English were unacquainted with the Irish language,
which I had taken much pains to learn, and understood pretty well.
Twenty of the Irish servants belonged to the gentlewoman above-mentioned, who,
together with a young man, her husband`'s brother, went along with us.
While we were on the coast of Ireland, where the wind detained us some weeks,
I overheard the Irish contriving how they should free themselves when they got to America.
To accomplish their design, they concluded to rise and kill the ship`'s crew,
and all the English, and to appoint the above-mentioned young man to navigate the vessel.
But, overhearing their conversation, I divulged their barbarous intention to the captain,
who acquainted the English with it.
The next day we headed for the shore,
but when we were at a short distance from the cove of Cork,
we lowered sail and dropped anchor,
under pretense that the wind would not permit us to continue our course.
The small boat was hoisted out,
and the passengers were invited to go and divert themselves on shore.
Along with a few others, the ringleader of the Irish servants went on shore.
This was all that was desired.
The others left him on shore and returned to the ship.
The captain then immediately ordered his men to weigh anchor, and hoist sail.
There were great outcries among the Irish for the young man left on shore,
but the captain said that the wind had changed direction,
and that he would not stay for his own son.
Thus the evil designs of the Irish servants were aborted, in a way they did not suspect.
And it was thought advisable to keep all a secret,
lest they should realize my involvement and injure me.
At length, however, they discovered that I understood their speech,
by my smiling at a story they were telling.
From this time on, they devised many ways to do me mischief,
for which several of them were punished.

On the 15th of the seventh month, which was nine weeks after we left Dublin,
we arrived at New York.
Here I was betrayed by the very men whose lives I had preserved.
The captain caused an indenture to be made,
and threatened me with a jail if I refused to sign it.
I told him that I could find means to satisfy him for my passage without becoming bound.
But he replied, that I might take my choice, either to sign the indenture he showed me,
or the previous one I had signed in Ireland should be in force.
In a fright, I signed the former;
for I had by this time learned the character of the
woman who first induced me to think of going to America.
She was a vile creature, and I feared that if I fell into her hands,
I should be treated very poorly.

In two weeks time I was sold as a servant.
At first I had not much reason to complain of the treatment I received;
but in a short time a problem arose, in which I was innocent,
which set my master against me and rendered his behavior inhuman.
It would be impossible for me to convey an adequate idea of the sufferings of my servitude.
Though my father was not rich, yet, in his house I lived well,
and I had been accustomed to do little besides my schoolwork;
but I now found it would have been better for me
if I had been brought up with less indulgence.
I was not allowed decent clothes; I was obliged to perform the lowest forms drudgery,
and even to walk barefoot in the snow.
I suffered the utmost hardship that my body was able to bear,
and the effect produced on my mind was nearly my ruin forever.

My master seemed to be a very religious man, taking the sacrament (so called) regularly,
and praying every night in his family; unless his prayer book could not be found, for,
to my knowledge, he never prayed without it.
His example, however, made me sick of his religion;
for though I had but little religion myself,
I had some idea of what religious people ought to be.
Respecting religion, my opinions began to waver;
I even doubted whether there was any such thing,
and began to think that the convictions I had felt from
my infancy were only the prejudices of my education.
These convictions seemed now to be lost;
and for some months I do not remember to have felt them.
My heart became hardened, and I was ready to conclude that there was no God.
The veneration I had felt for religious men in my infancy was entirely gone;
I now looked upon them in a very different manner.
My master`'s house was a common place of resort for the clergy;
and sometimes those who came from a distance lodged with him.
The observations I made on the conduct of these men confirmed me in my atheistical opinions.
They amused themselves in the evening with cards and songs,
and then a few moments afterwards, introduced prayers and singing psalms to Almighty God.
Often did I say to myself, "`If there is a God, he is a pure Being,
and will not hear the prayers of such polluted lips.`"

But He who has, in an abundant manner,
shown mercy to me--as will be seen in what follows--did
not long allow my mind to be perplexed with such doubts;
for in a moment, when my feet were on the brink of the bottomless pit,
He plucked me back.

To one woman, and to no other,
I told the nature of the problem which had happened two years before,
between my master and me.
By her means he heard of it, and though he knew that what I said was true,
he sent for the town`'s whipper to correct me.
I was called in.
My master never asked me whether I had said any such thing,
but simply ordered me to strip.
My heart was ready to burst.
I would as freely have given up my life than to have suffered such a disgrace.
"`If,`" said I, "`there is a God,
be graciously pleased to look down on one of Your most unhappy creatures,
and plead my cause;
for You know that what I have related is the truth;`" and had it not been
for a principle more noble than my master was capable of,
I would have told it to his wife.
Then fixing my eyes on the barbarous man, I said, "`Sir, if you have no pity on me,
yet for my father`'s sake spare me from this shame;`"
(for he had heard of my parents from several others),
"`and if you think I deserve such a punishment, then do it yourself.`"
He paced back and forth for a short time in the room,
and then told the whipper to leave and go about his business.
Thus I escaped without a blow; but my character nevertheless seemed to be lost.
Many reports of me were spread, which I bless God were not true.
But I suffered so much cruelty that I could not bear it;
and was tempted to put an end to my miserable life.
I listened to this temptation, and for that purpose went into the attic to hang myself.
Now it was that I became convinced there was a God, for as I entered the place,
horror and trembling seized me; and while I stood in terrible perplexity,
I seemed to hear a voice saying, "`There is a hell beyond the grave.`"
I was greatly astonished, and cried out, "`Oh God be merciful,
and enable me to bear whatsoever You in Your providence
shall bring or allow to come upon me.`"
I then went downstairs, but let no one know what I had been doing.

Soon after this I had a dream; and though some ridicule dreams,
this one seemed very significant to me, and I shall therefore mention it.
I thought I heard a knocking at the door, and when I had opened it,
there stood a grave woman, holding in her right hand a burning lamp.
And with a solid countenance, she fixed her eye upon me and said,
"`I am sent to tell you, that if you will return to the Lord your God, who created you,
He will have mercy on you, and your lamp shall not be put out in obscurity.`"
Her lamp then flamed up in an extraordinary manner, and she left me.
Then I awoke.

But alas, I did not give up to the "`heavenly vision,`" as I think I may call it;
and I was nearly caught in another snare of the most dangerous nature.
I was esteemed skillful at singing and dancing, in which I took great delight.
Once, falling in with a company of stage players who were then in New York,
they took a great fancy to me, as they said,
and invited me to become an actress among them.
They also added that they would find a means to release me from my cruel servitude,
and that I should live like a lady.
The proposal pleased me, and I took no small pains to qualify myself for them,
learning their playbooks even when I should have slept.
But, upon more serious reflection,
I decided against taking this step when I came to
consider what my father would think of it;
for he had finally forgiven my disobedience in marrying,
and had sent for me to return home, earnestly desiring to see me again.
Nevertheless, my proud heart would not allow me to return in so low a condition,
and I preferred bondage.

When I had served about three years, I bought out the remainder of my time,
and then worked at my needle, by which I could maintain myself handsomely.
But alas, it seems I was not sufficiently punished,
for after releasing myself from one cruel servitude, in the course of just a few months,
I entered into another one,
for life--by marrying a young man who fell in love with me for my dancing;
a poor motive for a man to choose a wife, or a woman a husband.
For my part, I was in love with nothing that I saw in him;
and it seems unexplainable to me that, after refusing several offers,
both in this country and Ireland, I would at last marry a man that I did not esteem.

My husband was a school-master.
A few days after we were married, we went from New York to a place called Westerly,
in Rhode Island, where he had engaged to keep a school.
With respect to religion he was much like myself, without any;
and when he was intoxicated, he would use the worst of oaths.
I do not mention this to expose him, but only to show the effect it had on myself;
for I saw myself ruined, being joined to a man I did not love,
and who was an example of no good to me.

We both seemed to be hastening towards destruction when I concluded,
that if I was not forsaken of heaven, I must alter my course of life.
To fix my affection on the Divine Being, and not to love my husband, seemed inconsistent.
So I daily desired, with tears,
that my affections might be directed in a right manner to him; and I can say,
that in a little time, my love was sincere.
I resolved to do my duty to God,
and expecting that I must come to the knowledge of His will by the Scriptures,
I read these sacred writings with a determination to follow their directions.
The more I read, the more uneasy I grew, especially about baptism.
I had reason to believe I had been sprinkled in my infancy, because,
at the age of thirteen, I was "`confirmed`" by the bishop;
yet I could not discover any precedent for this practice in Scripture.
In the course of my reading, I came to the passage where it is said,
"`He that _believes_ and is baptized,`"^
footnote:[Mark 16:16] etc.
Here I observed that belief (of which I was not capable
when sprinkled as an infant) must go before baptism.
I conversed frequently with the Seventh-day Baptists that lived in my neighborhood,
and at length, thinking it to be my real duty,
was in the winter baptized by one of their teachers.
I did not strictly join with them,
though I began to think that the seventh-day was the true sabbath,
and for a time kept it.
My husband did not oppose me, for he saw I grew more affectionate to him;
and as yet I did not refuse to sing and dance when he asked me,
though this way of amusing myself did not yield me so much satisfaction as formerly.

My husband and I now formed the plan of going to England,
and for this purpose we went to Boston, where we found a vessel bound to Liverpool.
We agreed for our passage, and expected to sail in about two weeks time;
but in the meantime,
another gentleman hired the vessel to carry himself and his attendants to Fayal,
and take no other passengers.
There being no other ship near sailing, we gave up our design,
though we remained in Boston for several weeks.
My mind was still not satisfied with regard to religion.
I had reformed my conduct, and was accounted by those who knew me a sober woman;
yet I was not content, for I expected to find the fruits of such a change.
And though several thought me to be religious, I dared not think so of myself.
I conversed with people of all societies, as opportunity offered,
several of whom thought I was of their persuasion; however, I joined strictly with none,
but resolved never to leave off searching until I found the truth.
This was in the twenty-second year of my age.

While we were in Boston, I went one day to the Quakers`' meeting,
where I heard a woman Friend speak, at which I was a little surprised.
I had been told of women`'s preaching, but had never heard it before;
and I looked upon her with pity for her ignorance, and with contempt for her practice,
saying to myself, "`I`'m sure you`'re a fool, and if ever I turn Quaker,
which will never be, I will not be a preacher.`"
Thus was my mind occupied while she was speaking.
When she had finished, a man stood up, who I could better bear.
He spoke sound doctrine on Joshua`'s good resolution,
"`As for me and my house we will serve the Lord.`"
After sitting down and remaining silent awhile, he began to pray,
which was accompanied with something so extraordinary and affecting,
that it drew tears from my eyes.

My husband was much given to wandering from one place to another,
which was very disagreeable to me, and so after leaving Boston, we went to Rhode Island,
and from there to the east end of Long Island, where he was hired to keep a school.
This place was principally settled by Presbyterians,
and I soon became acquainted with the most serious among them.
My poverty was no hindrance to my reception with people of the best credit,
with whom I frequently conversed; but the more I became acquainted with them,
the less I liked their opinions.
Many temptations in the meantime assaulted my unsettled mind.
Having been abroad one day,
I returned home and perceived that the people in whose house
we rented a room had left some flax in their apartment,
through which I needed to pass.
At the sight of it, I was tempted to steal some in order to make thread.
I went to it, and took a small bunch in my hand,
but was then so smitten with such remorse that I laid it down again, saying,
"`Lord keep me from so vile an action!`"
But the temptation to steal became stronger than before,
and I took the bunch of flax into my room.
When I came there, horror seized me, and with tears I cried out, "`Oh, God of mercy,
enable me to abstain from this vile action!`"
I then took the flax back,
and felt that pleasure which is only known to those who have resisted temptation.

My husband taking a different job further up the island, we changed our residence again.
The nearest place of worship there belonged to a congregation of the Church of England,
which, on the whole, I liked best, and so attended it.

A fresh exercise, of a very peculiar kind, now came upon me.
It was in the second month.
I was sitting by a fire, in company with several others, among whom was my husband;
when suddenly there was a loud clap of thunder, and a noise,
loud as from a mighty trumpet, pierced my ears with these words:
"`Oh eternity! eternity, the endless term of long eternity!`"
I was exceedingly astonished,
and while I was sitting as in a trance, I beheld something like a long roll,
written in black characters, and heard at the same time, a voice saying,
"`These are your sins, and the blood of Christ is not sufficient to wash them out.
This is shown you that you may confess your damnation to be just,
and not in order that you may be forgiven.`"
I sat speechless for a time, and at last got up trembling and threw myself on the bed.
The company thought my indisposition proceeded from a fright occasioned by the thunder;
but it was of another kind.

For several months after this I was almost in a state of despair,
and if at any time I endeavored to hope or lay hold of any gracious promise,
the tempter would insinuate that it was now too late; that the day of mercy was over,
and that I would only add to my sins by praying for pardon,
and provoke Divine vengeance to make of me a monument of wrath.
I was, as it were, already in torment.
I could not sleep, and ate but little.
I became extremely melancholy, and took no delight in anything.
Had all the world been mine, I would have given it gladly for one glimpse of hope.

My husband was shocked to see me so changed.
I, who once used to entertain him with singing and dancing,
in which he greatly delighted, could do it no longer.
My singing was turned into mourning, and my dancing into lamentation.

My nights and days were one continued scene of sorrow;
but I let no one know the state of my mind.
My husband used all the means in his power to divert my melancholy, but all was in vain.
The wound was too deep to be healed with anything less than the "`balm of Gilead.`"^
footnote:[Jeremiah 8:22; 46:11]
For fear of evil spirits I dared not,
nor would my husband permit me to spend much time alone; and if I picked up the Bible,
he would take it from me, exclaiming, "`How you have altered;
you used to be agreeable company, but now I have no comfort in you.`"
I endeavored to bear all of this with patience,
expecting that I should soon have to bear more than man could inflict.

I went to the priest, to see if he could relieve me; but he was a stranger to my case.
He advised me to take the sacrament and to amuse myself with innocent diversions.
He also lent me a book of prayers, which he said were suited to my condition;
but all of this was to no purpose.
As for diversions, they now felt burdensome; as for the sacrament,
I thought myself in a very unfit state to receive it; and as for prayers,
it appeared to me that if ever I could pray acceptably,
I would be enabled to do it without a book.
With a view to alleviate my grief,
my husband persuaded me to go to the razing of a building,
where much company had collected, but it had a contrary effect.
While there,
an officer came to summon a jury for the case of a man who had hanged himself;
and upon receiving this information,
I seemed to hear a voice within address me in this manner:--"`You
shall be the next to come to a similar end;
for you are not worthy to die a natural death.`"

For two months I was daily tempted to destroy myself,
often so strongly that I could scarcely resist.
Before I dared to walk alone, I left behind me every article which,
in an unguarded moment, I might use for this purpose;
fervently desiring at the same time,
that God would preserve me from taking the life He had given,
and which He would have made happy, if I had accepted His offers of grace,
by regarding the convictions He had favored me with from my youth.
During all this agony of mind, I could not shed one tear.
My heart was hardened, and my life miserable; but God in his infinite mercy,
delivered my soul from this bondage.
One night, as I lay in bed, bemoaning my condition, I cried out, "`Oh my God,
I beseech You, in Your mercy, look down upon me for Christ`'s sake,
who has promised that all manner of sins and blasphemies shall be forgiven.
Lord, if You will be graciously pleased to extend this promise to me,
an unworthy creature, trembling before You,
I will obey You in all that You shall command.`"
In an instant my heart was softened, and I was dissolved in a flood of tears.
I abhorred my past offenses, and admired the mercies of my God.
I could now hope in Christ my Redeemer, and look upon Him with an eye of faith.
I experienced what I had believed when the priest lent me his book, namely,
that when my prayers were acceptable, I would not need a book.
I now took the sacrament, and can say I did it with reverence and fear.

Being thus released from my deep distress, I seemed like another creature,
and now walked often alone without fear.
Once, as I was abhorring myself in great humility of mind,
I seemed to hear a gracious voice, full of love, say to me, "`I will never forsake you;
only obey Me in whatever I shall make known unto you.`"
I answered, "`My soul does magnify the God of mercy.
If You will dispense Your grace, the rest of my days shall be devoted to serve You.
And if it be Your will that I should beg my bread,
I will submit with contentment to Your providence.`"

I now began to think of my relations in Pennsylvania, whom I had not yet seen.
My husband gave me liberty to visit them,
and I obtained a certificate from the priest in order that, if I made any stay,
I might be received as a member of the church wherever I came.
My husband accompanied me to the Blazing-star ferry, saw me safely over the water,
and then returned home.
On my way, I fell from my horse, and for several days was unable to travel.
I abode at the house of an honest Dutchman, who, with his wife,
paid me the utmost attention, and would receive no recompense for their trouble.
I left them with sentiments of deep gratitude for their extraordinary kindness,
and they told me, if ever I came that way again, I must lodge with them.
I mention this, because I shall have occasion to allude to it hereafter.

When I came to Trenton ferry,
I felt no small disappointment upon hearing that my relations were all Quakers;
and what was worst of all, that my aunt was a preacher among them.
I was exceedingly prejudiced against this people,
and often wondered how they could call themselves Christians.
I regretted my coming, and was almost inclined to turn back;
yet as I was so far on my journey, I proceeded,
though I expected but little comfort from my visit.
How little did I suspect that it would bring me to the knowledge of the Truth!

I went from Trenton to Philadelphia by water, and from there to my uncle`'s on horseback.
My uncle was dead, and my aunt had married again; yet,
both she and her husband received me in the kindest manner.
I had scarcely been three hours in the house before
my opinion of these people began to alter.
I perceived a book lying upon the table, and being fond of reading, I picked it up.
My aunt observed me and said, "`Cousin, that is a Quaker book.`"
She saw I was not a Quaker, and supposed I would not like it.
I made her no answer, but queried to myself, "`What can these people write about?
I have heard that they deny the Scriptures,
and have no other Bible than George Fox`'s Journal,
and that they also deny the holy ordinances.`"
But, before I had read two pages, my heart burned within me,
and for fear I should be seen, I went out into the garden.
I sat down, and as the book was short, I read it through before I returned,
though I was often obliged to stop in order to give vent to my tears.
The fulness of my heart produced this involuntary exclamation, "`Oh my God, must I,
if I come to the knowledge of your Truth, be of this author`'s opinion,
who has sought You as I have done?
And must I join this people, to whom a few hours ago I preferred the Papists?
Oh God of my salvation, and of my life,
who has abundantly manifested Your long-suffering and tender
mercy in redeeming me from the lowest hell;
I beseech You to direct me in the right way, and to keep me from error.
Then I will perform my covenant,
and think nothing too near to part with for Your name`'s sake!`"

After having collected myself, I washed my face,
that it might not be perceived I had been weeping.
In the night I got but little sleep;
for the enemy of mankind haunted me with his insinuations,
suggesting that I was one who wavered and was not steadfast in faith;
advancing several texts of Scripture against me, as that,
"`in the latter days there should be those who would deceive the very
elect;`" and that this was the sort of people that I was amongst,
and that I was in danger of being deluded, etc.
Believing that I had been warned in this manner,
I resolved to be aware of these deceivers,
and for some weeks did not touch one of their books.
The next, day, being the first day of the week, I was desirous of going to church,
which was about four miles distant; but being a stranger,
and having no one to go with me, I gave up the idea;
and seeing that most of the family were going to their meeting, I went there with them.

As we sat in silence, I looked over the meeting and said to myself,
"`These people sit in silence like fools!
How much better would it be to stay at home and read the Bible, or some other good book,
than to come here and go to sleep.`"
As for me, I was very drowsy; and while asleep, I nearly fell off the bench.
This was the last time I ever fell asleep in a meeting.
I then began to be lifted up with spiritual pride, and to think myself better than they;
but this disposition of mind did not last long.
It may seem strange, that after living so long with one of this society in Dublin,
I would yet be such a stranger to them.
In answer, let it be considered that while I was there, I never read any of their books,
nor went to a single meeting.
Besides, I had heard such accounts of them as made me think that,
of all religious societies, they were the worst.
But He who knew the sincerity of the heart, looked upon my weakness with pity.
I was soon permitted to see my error,
and shown that these were the people to whom I must to join.

A few weeks afterwards, there was an afternoon meeting at my uncle`'s,
at which a minister named William Hammans was present.
I was highly prejudiced against him when he stood up, but I was soon humbled;
for he preached the Gospel with such power that I
was obliged to confess it was the truth.
But, though he was the instrument of assisting me out of many doubts,
my mind was not yet wholly freed from them.
For the morning before this meeting, I had been disputing with my uncle about baptism,
which also happened to be the subject handled by this minister.
And though his sermon removed all my scruples on this point beyond objection,
yet I seemed reluctant to believe that what I had heard proceeded from divine revelation,
and I accused my aunt and uncle of having spoken of me to the Friend.
Nevertheless, they cleared themselves,
telling me that they had not seen him since my coming to their house,
until he came into the meeting.
I then viewed him as a messenger of God to me, and laying aside my prejudices,
I opened my heart to receive the truth.

Oh, the beauty of the truth then began to be shown to me,
together with the glory of all who continued faithful to it.
I also saw into the emptiness of all shadows and types, which,
though proper in their day, were now, by the coming of the Son of God, at an end,
and everlasting righteousness (which is a work in
the heart) was to be established in their place.
I was permitted to see that all I had previously
gone through was to prepare me for this day,
and that the time was near when it would be required of me to go
and declare to others what the God of mercy had done for my soul.
I was much surprised at this, and desired to be excused,
lest I should bring dishonor to the Truth and cause His holy name to be evilly spoken of.
But I let no one know of these things.
Indeed, I feared being discovered, and did not even have the appearance of a Friend.

I then was hired to keep school, and hearing of a position for my husband, I wrote,
and requested him to come, though I did not let him know how it was with me.

I loved to be at meetings, but did not love to be seen going to them on week-days,
and therefore walked to the meetinghouse from my school through the woods.
Notwithstanding all my care, the neighbors, who were not Friends,
soon began to revile me with the name of Quaker, adding,
that they supposed I intended to be a fool and become a preacher.
Thus I received the same censure which, about a year previous,
I had passed on one of the handmaids of the Lord in Boston.
I was so weak in the faith that I could not bear the reproach,
and in order to change their opinion,
I went into greater excess of apparel than I felt
freedom to do even before I was acquainted with Friends.
In this condition I continued until my husband came, and then began the trial of my faith.

Before he reached me, he heard I had turned Quaker;
at which he stamped his foot and said, "`I would rather have heard she was dead!
For, though I love her, if it be so, then all my comfort is gone.`"
After an absence of four months, he came to me, and I arose and said to him,
"`My dear, I am glad to see thee.`"
Hearing the word __thee,__ he flew into a great rage, exclaiming,
"`The devil thee, thee, thee! Don`'t thee me!`"
I endeavored by every mild means to pacify him,
and at length got him in conditions to speak to my relations.
As soon as we were alone, he said to me,
"`I see your Quaker relations have made you one.`"
I replied that they had not, which was true.
He said he would not stay among them; and having found a place that suited him,
he took a job, and came directly back to fetch me, walking, in one afternoon,
thirty miles in order to keep me from attending the meeting the next day,
which was a first-day.
After resting the next day, he took me to the place of his employment,
and to the lodgings he had rented at the house of a churchwarden.
This man was a bitter enemy of Friends,
and did all that he could to irritate my husband against them.

Though I did not dress like a Friend, they all believed me to be one.
When this churchwarden and my husband would mock and revile, I sat in silence,
though every now and then an involuntary sigh broke from me, at which he would say,
"`There!
Did not I tell you your wife was a Quaker, and she will become a preacher.`"
On one such occasion, my husband came up to me in a great rage,
and shaking his hand over me, said, "`It would be better for you to be hanged.`"
I was seized with horror,
and again was plunged into a despair which continued nearly three months.
I was afraid that, by denying the Lord, the heavens would be shut against me.
I walked much alone in the woods, and there--where no eye could see,
nor any ear hear me--I lamented my miserable condition.
Often have I wandered about from morning till night without food.
I was brought so low that my life became a burden to me,
and the devil seemed to vaunt that, though the sins of my youth were forgiven me,
yet now I had committed an unpardonable sin, and hell would inevitably be my portion,
and my torments would be greater than if I had hanged myself at first.

In the night, under this painful distress of mind, I could not sleep;
and if my husband perceived me weeping, he would revile me for it.
At length, when he and his friend thought themselves unable to persuade me,
he went to the priest at Chester to inquire what he could do with me.
This man knew I was a member of the church of England, for I had shown him my certificate.
His advice was to take me out of Pennsylvania,
and settle in some place where there were no Quakers.
My husband replied that he did not care where we went,
if he could only restore me to my natural liveliness of temper.
As for me, I had no resolution to oppose their proposal, nor did I much care where I went.
Indeed, I seemed to have nothing to hope for,
and daily expected to be made a victim of Divine wrath,
being possessed with the idea that this would be by lightning.

When the time of our removal came, I was not permitted to bid farewell my relations;
and as my husband was poor, and kept no horse, I was obliged to travel on foot.
We came to Wilmington, fifteen miles, and from there to Philadelphia by water.
Here we stopped at a tavern, where I became the spectacle and discourse of the company.
My husband told them his wife had become a Quaker, and he designed, if possible,
to find out a place where there were none.
I thought to myself, "`I was once in a condition to deserve that name,
but now it is over with me.
Oh that I might, from a true hope, once more have an opportunity to confess the truth!
Even if I was sure to receive of all manner of cruelties, I would not regard them.`"
Such were my thoughts, while he was entertaining the company with my story,
in which he told them that I had been a good dancer,
but now he could neither get me to dance or to sing.
One of the company then jumped up and said, "`I`'ll fetch a fiddle,
and we`'ll have a good dance;`" a proposal with which my husband was pleased.
When the fiddle was brought, my husband came and said to me, "`My dear,
shake off that gloom, and let us have a civil dance.
You would dance now and then when you were a good churchwoman,
and that`'s better than being a stiff Quaker.`"
I had taken up the resolution not to comply with his request,
whatever might be the consequences.
I let him know this, though I dared say but little, for fear of his fierce temper.

He then pulled me round the room, till the tears fell from my eyes,
at the sight of which the musician stopped and said "`I`'ll play no more;
leave your wife alone.`"
A person in the company, who came from Freehold, in East Jersey, said,
"`I see your wife`'s a Quaker, but if you`'ll take my advice,
you need not go so far as you intend.
Come and live with us; we`'ll soon cure her of her Quakerism,
and we need a school-master and a school-mistress too.`"
My husband consented, and a happy change it was for me, as will shortly be seen.

The reward of peace was granted me for refusing to dance;
and I then rejoiced more than if I had been made mistress of great riches.
So with tears, I prayed, "`Lord, I dread to ask, and yet without Your gracious pardon,
I am miserable.
I therefore fall down before Your throne, and implore mercy at Your hand.
O Lord, once more, I beseech You, try my obedience,
and then I will obey you in whatever you command,
and will not fear to confess you before men.`"
My cries were heard,
and it was shown to me that "`the Lord delights not in the death of a sinner.`"
My soul was again set at liberty, and I was enabled to praise him.

On our way to Freehold,
we visited the kind Dutchman whom I mentioned in a former part of this narrative.
He made us welcome, and invited us to spend a day or two with him.
During our stay, we went to a large meeting of Presbyterians,
where there was also the trial of one of their priests who had been charged with drunkenness.
I perceived such great divisions among the people respecting who should be their shepherd,
that I pitied them.
Some insisted on having the old offender restored;
others wished to appoint a young man whom they had had on trial for some weeks;
still others were for sending to New England to request a new minister.
In reply to this suggestion, a man addressed himself to the chief speaker and observed,
"`Sir,
when we have paid at the expense (which will not
be small) of fetching this gentleman from New England,
perhaps he will not stay with us.`"
"`Don`'t you know how to make him stay?`"
said another.
"`I`'ll tell you; simply give him a large salary, and he`'ll certainly stay.`"
I listened attentively to the debate,
and it plainly appeared to me that these mercenary preachers were actuated by one motive,
which was not the regard for souls, but the love of money.
I had known one of these men,
called a "`reverend divine,`" whom these people almost adored,
who left his flock in Long Island and removed to Philadelphia in order to get more money.
I myself have heard some on the island say that they had almost
impoverished themselves in their attempts to keep him;
but, being unable to equal what he was offered at Philadelphia, he left them.
Surely these are shepherds who regard the fleece more than the flock.
And though they say that they are the ambassadors of Christ,
yet there are lies found in there mouths; for His command it is,
"`Freely you have received, freely give.`"

On our way to Freehold, as we came to Stony Brook,
my husband turned towards me and tauntingly said, "`Here`'s one of Satan`'s synagogues;
don`'t you dare run to it.
I hope to see you cured of your new religion.`"
A little further on we came to a large stream of water, over which there was no bridge,
and being strangers to the area we knew of no way to avoid passing through it.
He carried over our clothes, which we had in bundles;
and I took off my shoes and walked through the water in my stockings.
It was in the twelfth month; the weather was very cold and snow lay on the ground,
but it was the concern of my heart that the Lord would sanctify
all my afflictions to me and give me patience to bear them.

After walking nearly a mile we came to a house, which proved to be a sort of tavern.
My husband ordered some spirituous liquors, and I got some weakened mulled cider,
which made me extremely sick; so that after we had walked a little past the house,
I was too faint to proceed, and fell down.
"`What`'s the matter now?`"
said my husband, "`What, are you drunk?
Where`'s your religion now?`"
He knew I was not drunk, and at that time I believe he pitied me,
even though he spoke in this manner.
After I had recovered a little,
we continued on and came to another tavern where we lodged.

The next day as we journeyed, a young man driving an empty cart overtook us.
We asked him to let us ride, and he readily granted the request.
There was a time when I would not have been seen riding in a cart,
but my proud heart was now humbled, and I did not regard how it looked.
This cart belonged to a man in Shrewsbury,
and was to continue on through the place of our destination.
Because of a failure on the part of the driver,
we soon had the care of the cart and horses to ourselves,
and arrived with it at Freehold.
My husband would have had me stay there while he went to see the horses safely home;
but I told him, no, since he had led me through the country like a vagabond,
I would not stay behind him.
We therefore went together, and lodged that night at the house of the owner of the cart.

The next day on our return to Freehold, we met a man who said to my husband, "`Sir,
are you a schoolmaster?`"
He answered, "`Yes.`"
The stranger replied, "`I have come to tell you of two new school-houses,
two miles apart, both of which are in need of a schoolmaster.`"
How this person came to hear of us, who had arrived just the night before,
I never understood.
And I was glad he was not a Quaker,
lest it should have been thought a plot by my husband,
to whom I turned and said,--"`My dear, look upon me with pity,
if you have any affection left for me, which I hope you have,
for I am not conscious of having done anything to alienate it.
Here is an opportunity to settle us both,
and I am willing to do all in my power towards getting an honest livelihood.`"
After a short pause, he consented to go with the young man.
Along our way, we came to the house of a worthy Friend who was a preacher,
though we did not then know it.
I was surprised to see the people behave so kindly to us.
We had not been long in the house before we were invited to lodge there for the night,
being the last day of the week.

My husband accepted the invitation, saying, "`My wife has had a tedious travel,
and I pity her.`"
These kind expressions affected me, for I heard them very seldom.
The Friend`'s kindness could not have proceeded from my appearing like a Quaker,
because I had not yet altered my form of dress.
The woman of the house, after we had concluded to stay, fixed her eyes upon me, and said,
"`I believe you have met with a great deal of trouble,`"
to which I made but little answer.
My husband then observing they were of that sort
of people whom he had so much endeavored to shun,
gave us no opportunity for discourse that night.
But the next morning, I let this kind woman know a little of my situation.

When their meeting time came I longed to go, but dared not ask my husband`'s permission.
As the Friends were getting ready themselves, they asked him if he would accompany them,
mentioning that they knew those who were to be his employers,
and if they were at the meeting, they would speak to them.
He consented to go.
The woman Friend then said, "`And will you allow your wife to go too?`"
This request he denied;
but she answered his objections so prudently that he could not be angry,
and at last consented.
I went with joy, and a heavenly meeting it was.
My spirit did rejoice in the God of my salvation.
May I ever, in humility, preserve the remembrance of His tender mercies to me.

By the end of the week, we got settled in our new situation.
We took a room in a Friend`'s house, one mile from each school,
and eight miles from the meetinghouse.
I now deemed it proper to let my husband see that I was determined to join with Friends.
When first-day came, I directed myself to him in this manner; "`My dear,
are you willing to let me go to the meeting?`"
He flew into a rage, and replied, "`No, you shall not!`"
Speaking firmly, I told him, "`As a dutiful wife,
I am ready to obey all your lawful commands;
but when your commands impose upon my conscience, I cannot obey them.
I have already wronged myself in having done it too long.
Though you are near to me, and as a wife ought, I love you; yet God,
who is nearer than all the world to me,
has made me sensible that this is the way I should go.`"
I then added, "`This is no small cross to my own will; but I have given up my heart,
and I trust that He who has called for this act of obedience will enable me,
for the remainder of my life, to keep steadily devoted to His service;
and I hope I shall not on this account make the worse wife.`"
My words, however, were to no purpose; for he continued inflexible.
But as I had now put my hand to the plough and resolved not to draw back,
I therefore went without his permission.
I expected he would immediately follow me and force me back, but he did not.
I stopped at the house of one of the neighbors,
and after requesting a girl to show me the way,
I walked on rejoicing and praising God in my heart.

Thus for some time, I had to go eight miles on foot to meeting,
which I never thought hard.
My husband at this time had a horse, but he would not allow me to ride it;
nor when my shoes were worn out, did he let me have a new pair.
But though he hoped in this way to keep me from meeting, it did not hinder me.
I have tied my shoes around with strings in order to keep them on my feet.

Finding that all the means he had yet used could not alter my resolution,
he several times struck me severe blows.
I endeavored to bear all with patience,
believing that the time would come when he would see that I was in the right.
Once he came up to me, took out his penknife and said, "`If you go to meeting tomorrow,
I will cripple you with this knife, for you shall not be a Quaker.`"
I made him no answer.
In the morning I set out as usual, and he did not attempt to harm me.

Having despaired of recovering me himself, he fled to a priest for help,
whom he told that I had been a very religious woman in the way of the Church of England,
of which I was a member and had a good certificate from Long Island,
but that now I was bewitched and had turned Quaker, which almost broke his heart.
He therefore requested that this priest, as one who had the care of souls,
would come and pay me a visit and use his endeavors to reclaim me,
which he hoped by the blessing of God, would be done.
The priest consented and fixed a time for his coming, which was two weeks from that day,
as he said he could not come sooner.
My husband came home extremely pleased, and told me of it.
I replied with a smile,
that I trusted I would be enabled to give a reason for the hope that was within me;
yet I believed at the same time, that the priest would never trouble himself about me,
which proved to be the case.

Before the day appointed came,
it was required of me to confess to the world what I was in a more public manner.
I felt it required of me to give up to pray publicly in our meeting.
I trembled at the prospect,
and would willingly have surrendered my life in order to be excused.
And what made this seem even harder to me,
was that I had not yet been taken in as a member of the Society,
having been kept from requesting membership for fear
that I might bring a scandal upon Friends.
I begged the Lord to be excused until I had joined, and then I would give up freely.
But His answer to me was, "`I am a covenant-keeping God,
and the word that I spoke to you when I found you in distress--even
that I would never forsake you if you would be obedient to what
I would make known unto you--I will assuredly fulfill.
If you refuse, my Spirit shall not always strive with you.
Fear not, I will make a way for you through all your difficulties,
which shall be many for My name`'s sake.
Be faithful, and I will give you a crown of life.`"
In response to this language, I answered, "`Your will, O God, be done.
I am in Your hand, do with me according to Your word.`"
I then kneeled and prayed in the meeting.

This day, as usual, I had gone to meeting on foot.
While my husband (as he afterwards told me) was lying on the bed,
these words crossed his mind: "`Lord, where shall I flee to escape You?`"
Upon which he arose, and seeing that it was raining,
got the horse and set off to fetch me, arriving just as the meeting broke up.
I got on horseback as quickly as possible,
lest he should hear I had spoken in the meeting.
He heard of it nonetheless, and as soon as we were in the woods, began by saying,
"`Why do you seek to make my life unhappy?
Could you not be a Quaker, without also turning a fool in this manner?`"
I answered in tears, "`My dear, look upon me with pity if you have any.
Can you possibly think that I, in the bloom of my days, would bear all that you know of,
and much that you know not of, if I did not feel it to be my duty?`"
These words touched him, and he said, "`Well then, I will give you up.
I see it won`'t avail to strive.
If this is of God, I cannot overthrow it; and if it is of yourself, it will soon fall.`"
I saw the tears in his eyes, at which I was overcome with joy,
and felt I had begun to reap the fruits of my obedience.
But my trials were not yet over.

The time appointed for the priest to visit me arrived, but no priest appeared.
My husband went to fetch him, but he refused to come, saying he was busy,
which so displeased my husband that he never went to hear him again,
and for some time went to no place of worship.

My faith was now assaulted so strongly in another way,
that all my former trials seemed but trifling in comparison to it.
This trial came upon me unexpectedly, by hearing a woman speak of a book she had read,
in which it was asserted that Christ was not the Son of God.
As she spoke, a voice within me seemed to answer, "`He is not.
It is all a fancy, and the contrivance of men.`"

Thus, once again, I was filled with inexpressible trouble,
which continued about three weeks; and again I sought desolate places,
where I might cry out to the Lord.
During this time I laid whole nights without sleep.
I thought myself deserted of God, but did not let go of my trust in Him.
I kept alive a hope,
that He who had delivered me (as it were) out of the paw of the bear,
and the jaws of the lion, would in His own good time,
deliver me from this temptation also.
Indeed, this was at length my blessed experience; and I found the truth of His words,
that all things shall work together for the good of those who love and fear Him.
For these trying exercises were to prepare me for further services in His cause;
and I have learned it is necessary for His ministers
to experience many baptisms into death,
that they may thereby be more able to speak to the conditions of others.

This happened just after my first appearance in the ministry,
and Friends had not yet come to talk with me about joining the Society.
They did not well know what to do until I felt it
required of me again to speak in a meeting,
which was not for some time,
and then the Monthly Meeting appointed four Friends to pay me a visit.
They left me well-satisfied with the conference, and I joined the Society.
My husband still attended no place of worship.
One day he said to me, "`I would go to meeting with you,
only I`'m afraid I shall hear your preach, which I cannot bear.`"
I used no persuasions.
When meeting-time came he got the horse, took me behind him and we went.
For several months, if he saw me preparing to arise he went out;
till one day I rose before he was aware, and then as he afterwards acknowledged,
he was ashamed to go out.

From this time forward he left off the practice,
and never hindered me from going to meeting.
Though he did not take up the cross, yet his judgment was convinced;
and sometimes melting into tears, he would say to me, "`My dear,
I have seen the beauty there is in the Truth, and that you have followed the right way,
in which I pray God preserve you.`"
I told him that I hoped He who had given me strength would also do the same for him.
"`Oh,`" said he, "`I cannot bear the reproach that you do, to be called a turn-coat,
and become a laughing-stock to the world.
But I will no longer hinder you.`"
This I considered a favor,
and a little hope remained that my prayers on his account would be heard.

We lived in a small house by ourselves, which, though mean,
and though we had little to spend on it (our bed being no better than straw),
I was truly content.
The only desires I had were for my own preservation,
and to be blessed with the reformation of my husband.
He was connected with a group of men that he feared would make sport of him,
which indeed they did.
They asked him when he planned to commence preaching,
for they saw he intended to turn Quaker,
and that he seemed to love his wife more since she became one than before.
They used to come to our house, and provoked him to sit up and drink with them,
sometimes till near the break of day, while I have been sorrowing in a stable.
Once, as I sat in this condition, I heard him say to his company,
"`I cannot bear any longer to afflict my poor wife in this manner;
for whatever you may think of her, I believe she is a good woman.`"
He then came to me and said, "`Come in my dear,
God has given you a great deal of patience.
I`'ll put an end to this practice.`"
That was the last time they sat up at night.

My husband then suggested that if he lived in any place,
where it was not known that he had been so bitter against Friends, he could do better.
I objected to this, fearing it would not be for his benefit.
Frequently in a broken and affectionate manner, he condemned his ill-treatment of me.
I answered that I hoped it had been for my good,
and therefore desired he would not be afflicted on that account.
According to the measure of grace received, I did what I could,
both by example and precept, for his good.
My advice was to stay where he was,
as I was afraid he would grow weaker in his good resolutions if he moved to another town.

All I could say would not avail.
Hearing of a place at Bordentown he went there, but he was not suited for the job.
He next removed to Mount Holly, where we settled.
Before long, we each had a good school, got our house pretty well furnished,
and we might have done very well.
Nothing seemed lacking to complete my happiness,
except for the reformation of my husband, which I soon had reason to doubt I would see.
And alas, it turned out according to my fears, for he addicted himself much to drinking,
and grew worse than he was before.

Sorrow was again my lot.
I prayed for patience to bear my afflictions,
and to submit to the dispensations of Providence.
I did not murmur;
nor do I remember that I ever uttered any harsh expressions
except on the following occasion.
My husband coming home a little intoxicated, a state in which he was very irritable,
and finding me at work by a candle, he put it out,
giving me at the same time a box on the ear, saying, "`You don`'t earn your light.`"
At this unkind treatment, which I had not been used to for the last two years,
I was somewhat angry, and said, "`You are a vile man.`"
He then struck me again; but by then my anger had cooled,
and I received the blow without so much as a word in return.
This also displeased him, and he went on in a wild manner,
uttering such expressions of despair as,
he believed he was "`predestined to damnation,`"
and "`did not care how soon God struck him dead.`"
I said very little, until at length in the bitterness of my soul,
I prayed in these words: "`Lord, look down on my afflictions,
and deliver me by some means or other.`"
My prayer was granted, but in such a manner that I thought would perhaps end my life.
My husband went to Burlington, where he got drunk,
and then enlisted as a common soldier to go to Cuba, in the year 1740.
I had drunk many bitter cups, but this seemed the bitterest of them all.
I blamed myself for making such a request, which I was afraid had displeased the Lord,
who had, in displeasure, granted it for my punishment.

But I have since had cause to believe that he received some benefit by this rash act;
for in the army,
he did what he could not do at home--he suffered for the testimony of Truth.
When his troop had prepared to engage in battle, he then refused to fight.
He was therefore whipped and brought before the general,
who asked him why he enlisted in the army if he would not fight.
"`I did it,`" he said, "`in a drunken frolic, when the devil had the better of me.
But now my judgment is convinced that I ought not to fight; and I will not do it,
whatever I suffer.
I have but one life, and you may take it if you please, for I`'ll never take up arms.`"
He adhered to this resolution, but by their cruel treatment of him in consequence,
he was so much disabled that the general sent him to Chelsea Hospital, near London.
Within nine months afterwards he died at this place, and I hope made a good end.

I never thought him to be the worst of men.
If he had permitted grace to have its perfect work,
I would have been happy in the lowest situation of life.
I have had cause to bless God, for enabling me in the station of a wife, to do my duty;
and now that I am a widow, I submit to His will.
May I still be preserved by the arm of Divine Power;
and never forget the tender mercies of my God,
the remembrance of which often bows my soul in humility before His throne.
"`Lord, what was I, that you should reveal to my soul the knowledge of Your truth,
and do so much for one who deserved your displeasure?
May you, O God, be glorified and may I be abased.
It is Your own works that praise You; and truly,
to the humble soul you make every bitter thing sweet.`"

[.asterism]
'''

[.emphasized]
Elizabeth`'s husband had been gone two or three years before she heard of his death.
He left her nearly eighty pounds in debt, which, by law, she was not obliged to pay.
Nevertheless,
as several creditors complained and said they would not
have trusted her husband if it had not been for her sake,
she engaged to satisfy them all as fast as she could.
She settled steadily into the business of school-keeping, and by this means,
together with her needlework, she maintained herself handsomely.
She gradually paid off the above-mentioned debts,
and had nearly discharged them all during her widowhood,
though she also travelled much in the meantime as a minister.

[.emphasized]
In the ninth month, 1746, she married again to Aaron Ashbridge,
in Burlington, West Jersey.
In the year 1753,
apprehending it required of her to visit the meetings
of Friends throughout England and Ireland,
she left her habitation with the consent of her husband,
and the unity and approbation of Friends,
and performed a religious visit to these nations,
but at last fell dangerously ill in the city of Cork.
The 7th of the fifth month, 1755, being sorely afflicted with pain of body,
she expressed her desire for patience under her sufferings, saying,
"`Oh dearest Goodness, grant me patience till my change comes,
and then do not forsake me, oh Lord of my life!`"
At another time, when in extreme pain, she cried out, "`Lord, look down upon me.
May patience, my old companion, not leave me now.`"
At one time she said, "`I have endeavored to live without a will of my own;
and hope I have borne my afflictions with a degree of Christian fortitude.`"
Having grown weaker for several days, she departed this life in a quiet frame,
the 16th of the fifth month, 1755, at the age of forty-two years,
and was buried in Friends`' burying-ground at Ballybrumhill.
